#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
make_provenance.py -- one command behind the adiabatic validation table.

Written for CQG-116884, referee major comments 7 and 10.

Referee major 7:
    "The validation should come from one traceable dataset.  Figure 3 reports a
     common log-log slope 2.12 +/- 0.03, whereas Table A3 reports slopes from
     approximately 1.95 to 2.16. [...] the figure, table, raw data, fit,
     uncertainty estimate, and file hash should be generated by the same
     archived command.  The paper should state the epsilon-window and
     demonstrate that the fitted interval remains uniformly away from the
     excluded loci."

Referee major 10:
    "[...] a manifest mapping each equation, figure, and table to one command
     and one checksum."

Both complaints have the same root cause: the numbers and hashes in the
manuscript were transcribed by hand from separate runs, so they drifted.  When
this was checked, the same two files carried THREE different SHA-256 prefixes --
one printed in the manuscript, one in the v1.0 release the referee cloned, and a
third in the working tree.  Re-copying them by hand would only reset the clock.

This script therefore GENERATES them.  It

  1. runs each validation script as a subprocess and captures its output,
  2. parses the reported log-log slopes and their 1-sigma uncertainties,
  3. records the epsilon-window actually used and the fitted radial interval,
     together with its separation from the excluded loci,
  4. computes the SHA-256 of every script involved,
  5. writes  adiabatic_slopes.json   (machine-readable record)
             adiabatic_slopes.tex    (LaTeX fragment, \\input by paper2.tex)
             MANIFEST.tsv            (artefact -> command -> checksum)

Because paper2.tex \\input's the generated fragment, the printed slopes and
hashes cannot drift from the archive again.

Usage:
    python3 make_provenance.py            # run everything, write all outputs
    python3 make_provenance.py --check    # verify outputs are up to date, exit 1 if not
    python3 make_provenance.py --manifest # manifest only (fast, no subprocesses)
"""
from __future__ import annotations

import hashlib
import json
import re
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent          # .../paper2/provenance
PAPER2 = HERE.parent                            # .../paper2
NSM = PAPER2.parent                             # .../NonStationaryMetrics
ROOT = NSM.parent                               # repository root


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------
def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for block in iter(lambda: fh.read(65536), b""):
            h.update(block)
    return h.hexdigest()


def short(path: Path) -> str:
    """SHA-256, first 12 hex -- the form printed in the manuscript."""
    return sha256(path)[:12]


def rel(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def run(script: Path, timeout: int = 3600) -> tuple[str, float]:
    t0 = time.time()
    proc = subprocess.run([sys.executable, script.name],
                          cwd=script.parent, capture_output=True,
                          text=True, timeout=timeout)
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout + "\n" + proc.stderr + "\n")
        raise RuntimeError(f"{script.name} exited {proc.returncode}")
    return proc.stdout, time.time() - t0


# --------------------------------------------------------------------------
# the two adiabatic validation runs
# --------------------------------------------------------------------------
VALIDATION = NSM / "ThakurtaMetric" / "fig_phi_validation_corrected.py"
EXACT = NSM / "ThakurtaMetric" / "adiabatic_first_order_exact.py"

# "<label>: leading slope 1.01+/-0.00  exact slope 2.12+/-0.03"
RE_VAL = re.compile(
    r"^(?P<label>.+?):\s*leading slope\s*(?P<lead>[-\d.]+)\+/-(?P<lead_e>[-\d.]+)"
    r"\s+exact slope\s*(?P<exact>[-\d.]+)\+/-(?P<exact_e>[-\d.]+)\s*$")
RE_SLOPE = re.compile(r"SLOPE\(full PT, S_D\) vs TRUE flow\s*=\s*(?P<s>[-\d.]+)"
                      r"\s+res@(?P<eps>[\d.]+)=(?P<res>[-\deE.+]+)")
RE_ROBUST = re.compile(r"robust SLOPE\s*=\s*(?P<s>[-\d.]+)")

# the epsilon-window is a literal in fig_phi_validation_corrected.py; read it
# back from the source rather than restating it, so the two cannot disagree.
RE_EPSS = re.compile(r"epss\s*=\s*np\.array\(\[([^\]]+)\]\)")


def epsilon_window() -> list[float]:
    m = RE_EPSS.search(VALIDATION.read_text())
    if not m:
        raise RuntimeError("could not read the epsilon window from "
                           f"{VALIDATION.name}")
    return [float(x) for x in m.group(1).split(",")]


def parse_validation(out: str) -> list[dict]:
    rows = []
    for line in out.splitlines():
        m = RE_VAL.match(line.strip())
        if m:
            rows.append({
                "config": m.group("label").strip(),
                "leading_slope": float(m.group("lead")),
                "leading_sigma": float(m.group("lead_e")),
                "exact_slope": float(m.group("exact")),
                "exact_sigma": float(m.group("exact_e")),
            })
    if not rows:
        raise RuntimeError("no slope lines parsed from the validation run")
    return rows


def parse_exact(out: str) -> dict:
    m = RE_SLOPE.search(out)
    r = RE_ROBUST.search(out)
    if not m:
        raise RuntimeError("no slope line parsed from the exact run")
    return {
        "slope": float(m.group("s")),
        "residual_at": float(m.group("eps")),
        "residual": float(m.group("res")),
        "robust_slope": float(r.group("s")) if r else None,
    }


# --------------------------------------------------------------------------
# excluded loci
# --------------------------------------------------------------------------
# The first-order theorem is local on a compact regular subarc and excludes
# turning points, the freezing surface, the conformal stationary limit, chart
# singularities and moving-separatrix crossings.  Both runs fit on the radial
# window below; we report its separation from the nearest excluded locus.
FIT_INTERVAL = (8.0, 11.0)      # r/M, as used in both scripts
EXCLUDED = {
    "conformal stationary limit r_e = 2M": 2.0,
    "seed Kerr null surface r_+ (a=0.9)": 1.4358898943540673,
}


def locus_separation() -> dict:
    lo, hi = FIT_INTERVAL
    worst = min(lo - v for v in EXCLUDED.values())
    return {
        "fit_interval_r_over_M": [lo, hi],
        "excluded_loci": EXCLUDED,
        "min_separation_r_over_M": worst,
    }


# --------------------------------------------------------------------------
# finite-window bias of the fitted exponent
# --------------------------------------------------------------------------
RAW = NSM / "ThakurtaMetric" / "adiabatic_convergence_raw.npz"


def subwindow_drift() -> dict:
    """Refit the exponent on shrinking epsilon sub-windows.

    The residual is R(eps) = c2 eps^2 (1 + k eps + ...), so the LOCAL log-log
    slope is 2 + O(eps), not exactly 2: a least-squares fit over a finite window
    is biased upward by the cubic term.  The statistical sigma returned by the
    covariance measures fit quality, not that bias, which is why 2.12 +/- 0.03
    sits several sigma from 2 without being in tension with second order.

    The falsifiable statement is that the fitted exponent -> 2 as the window
    shrinks.  We test exactly that: drop the largest epsilon repeatedly and
    report the sequence of fitted slopes.
    """
    import numpy as np
    if not RAW.exists():
        return {"available": False,
                "note": "run fig_phi_validation_corrected.py first"}
    z = np.load(RAW, allow_pickle=True)
    n = sum(1 for k in z.files if k.startswith("eps_"))
    res = []
    for i in range(n):
        e = np.asarray(z[f"eps_{i}"], dtype=float)
        r = np.asarray(z[f"res_exact_{i}"], dtype=float)
        label = str(z[f"label_{i}"])
        seq = []
        for cut in range(0, len(e) - 2):           # keep at least 3 points
            ee, rr = e[:len(e) - cut], r[:len(r) - cut]
            s = float(np.polyfit(np.log(ee), np.log(rr), 1)[0])
            seq.append({"eps_max": float(ee[-1]), "n_points": len(ee),
                        "slope": round(s, 4)})
        res.append({"config": label, "fits": seq,
                    "slope_full_window": seq[0]["slope"],
                    "slope_narrowest": seq[-1]["slope"]})
    return {"available": True, "configs": res}


def report_subwindow(sub: dict) -> bool:
    if not sub.get("available"):
        print("   sub-window drift: raw data unavailable")
        return True
    print("   fitted exponent on shrinking epsilon sub-windows "
          "(bias -> 0 as the window shrinks):")
    ok = True
    for c in sub["configs"]:
        seq = " -> ".join(f"{f['slope']:.3f}" for f in c["fits"])
        moved = abs(c["slope_narrowest"] - 2.0) <= abs(c["slope_full_window"] - 2.0) + 1e-9
        print(f"     {c['config'][:42]:42s} {seq}"
              + ("" if moved else "   <-- NOT converging toward 2"))
        ok = ok and moved
    if ok:
        print("   every configuration moves toward 2 as eps_max decreases:")
        print("   consistent with O(eps^2) plus a cubic finite-window bias.")
    return ok


# --------------------------------------------------------------------------
# manifest
# --------------------------------------------------------------------------
# artefact -> (command, path-relative-to-root)
MANIFEST: list[tuple[str, str, str]] = [
    # --- claims verified symbolically -------------------------------------
    ("Prop. 3.1 (local classification at r_e), shape",
     "wolframscript -file verify_cusp_corner.wls",
     "NonStationaryMetrics/paper2/verification/verify_cusp_corner.wls"),
    ("Prop. 3.1 (local classification at r_e), dynamics",
     "wolframscript -file verify_marginal_hamilton.wls",
     "NonStationaryMetrics/paper2/verification/verify_marginal_hamilton.wls"),
    ("Prop. 3.2 (exterior retrograde separatrix), eq. (exterior-sep)",
     "wolframscript -file verify_exterior_separatrix.wls",
     "NonStationaryMetrics/paper2/verification/verify_exterior_separatrix.wls"),
    # --- adiabatic validation ---------------------------------------------
    ("Fig. (phi-true-dynamic) and Table A3 slopes",
     "python3 make_provenance.py",
     "NonStationaryMetrics/paper2/provenance/make_provenance.py"),
    ("true-dynamics validation run",
     "python3 fig_phi_validation_corrected.py",
     "NonStationaryMetrics/ThakurtaMetric/fig_phi_validation_corrected.py"),
    ("exact first-order PT run",
     "python3 adiabatic_first_order_exact.py",
     "NonStationaryMetrics/ThakurtaMetric/adiabatic_first_order_exact.py"),
    # --- computer-assisted proposition ------------------------------------
    ("CAP interval-arithmetic library",
     "python3 cap_full.py",
     "NonStationaryMetrics/cap_full.py"),
    ("CAP certificate at r0 = 10",
     "python3 no_inversion_schwarzschild_CAP_r0_10.py",
     "NonStationaryMetrics/no_inversion_schwarzschild_CAP_r0_10.py"),
    # --- figures -----------------------------------------------------------
    ("Fig. (master-pen)", "python3 fig_master_penetration_taut.py",
     "KerrScripts/fig_master_penetration_taut.py"),
    ("Fig. (atlas-tau), Fig. (atlas-t)", "python3 fig_atlas_tau_t.py",
     "KerrScripts/fig_atlas_tau_t.py"),
    ("Fig. (th-cusp)", "python3 cuspide_ergosfera.py",
     "NonStationaryMetrics/ThakurtaMetric/cuspide_ergosfera.py"),
    ("Fig. (sep3)", "python3 kerr_separatrix_trajectories.py",
     "KerrScripts/kerr_separatrix_trajectories.py"),
    ("Fig. (jpt-g2)", "python3 kerr_jpt_genus2_figure.py",
     "KerrScripts/kerr_jpt_genus2_figure.py"),
    ("Fig. (jcm-cap)", "python3 kerr_jcm_capture_figure.py",
     "KerrScripts/kerr_jcm_capture_figure.py"),
    ("shared figure style", "-", "NonStationaryMetrics/paper_style.py"),
    ("environment lock (Python stack + CAS version)", "-",
     "NonStationaryMetrics/requirements-lock.txt"),
    ("bibliography audit against the DOI registry", "python3 audit_refs.py",
     "NonStationaryMetrics/paper2/provenance/audit_refs.py"),
    ("bibliography audit by title, for entries with no DOI",
     "python3 audit_by_title.py",
     "NonStationaryMetrics/paper2/provenance/audit_by_title.py"),
]


def write_manifest() -> int:
    missing = 0
    lines = ["# artefact\tcommand\tpath\tsha256"]
    for artefact, command, path in MANIFEST:
        p = ROOT / path
        if not p.exists():
            lines.append(f"{artefact}\t{command}\t{path}\tMISSING")
            missing += 1
            continue
        lines.append(f"{artefact}\t{command}\t{path}\t{sha256(p)}")
    (HERE / "MANIFEST.tsv").write_text("\n".join(lines) + "\n")
    return missing


# --------------------------------------------------------------------------
# LaTeX fragment
# --------------------------------------------------------------------------
def tex_escape(s: str) -> str:
    return s.replace("_", r"\_")


def write_tex(data: dict) -> None:
    v = data["validation"]
    e = data["exact"]
    win = data["epsilon_window"]
    sep = data["loci"]
    lo, hi = sep["fit_interval_r_over_M"]

    exact_slopes = [r["exact_slope"] for r in v["rows"]]
    exact_sigmas = [r["exact_sigma"] for r in v["rows"]]
    common = (max(exact_slopes) - min(exact_slopes)) < 1e-9
    if common:
        slope_str = f"${exact_slopes[0]:.2f}\\pm{exact_sigmas[0]:.2f}$"
    else:
        slope_str = (f"${min(exact_slopes):.2f}$--${max(exact_slopes):.2f}$")

    lead = [r["leading_slope"] for r in v["rows"]]

    out = [
        "% ---------------------------------------------------------------",
        "% GENERATED FILE -- do not edit by hand.",
        "% Produced by paper2/provenance/make_provenance.py; see that file for",
        "% why these numbers are generated rather than transcribed",
        "% (CQG-116884, referee major comments 7 and 10).",
        f"% generated {data['generated_utc']}",
        "% ---------------------------------------------------------------",
        r"\newcommand{\provEpsWindow}{$\varepsilon\in\{"
        + ",\\,".join(f"{x:g}" for x in win) + r"\}$}",
        r"\newcommand{\provFitInterval}{$r/M\in[" + f"{lo:g},{hi:g}" + r"]$}",
        r"\newcommand{\provLocusSep}{"
        + f"{sep['min_separation_r_over_M']:g}" + r"\,M}",
        r"\newcommand{\provExactSlope}{" + slope_str + r"}",
        r"\newcommand{\provLeadSlope}{$"
        + f"{min(lead):.2f}" + r"$--$" + f"{max(lead):.2f}" + r"$}",
        r"\newcommand{\provExactRunSlope}{$" + f"{e['slope']:.2f}" + r"$}",
        r"\newcommand{\provExactRunResidual}{$" + f"{e['residual']:.2e}"
        .replace("e-0", r"\times10^{-").replace("e-", r"\times10^{-") + r"}$}",
        "",
        "% per-configuration rows of the validation run",
        r"\newcommand{\provValidationRows}{%",
    ]
    for r in v["rows"]:
        out.append(
            f"  {r['config']} & ${r['leading_slope']:.2f}\\pm"
            f"{r['leading_sigma']:.2f}$ & ${r['exact_slope']:.2f}\\pm"
            f"{r['exact_sigma']:.2f}$ \\\\")
    out.append("}")
    out.append("")
    sub = data.get("subwindow", {})
    if sub.get("available"):
        seqs = [" \\to ".join(f"{f['slope']:.3f}" for f in c["fits"])
                for c in sub["configs"]]
        out.append("% fitted exponent on shrinking epsilon sub-windows")
        out.append(r"\newcommand{\provSubwindowDrift}{$" + seqs[0] + r"$}")
        narrow = max(abs(c["slope_narrowest"] - 2.0) for c in sub["configs"])
        out.append(r"\newcommand{\provSubwindowNarrowest}{$"
                   + f"{2.0 + narrow:.3f}" + r"$}")
        # no math delimiters: the manuscript uses this inside $...$
        out.append(r"\newcommand{\provSubwindowEpsMax}{"
                   + f"{sub['configs'][0]['fits'][-1]['eps_max']:g}" + r"}")
        out.append("")
    out.append("% SHA-256 (first 12 hex) of every script behind the table")
    for name, h in data["hashes"].items():
        macro = "".join(w.capitalize() for w in
                        re.split(r"[^A-Za-z]+", Path(name).stem) if w)
        out.append(r"\newcommand{\provHash" + macro + r"}{\texttt{" + h + "}}")
    out.append("")
    out.append(r"\newcommand{\provHashLine}{%")
    items = [r"\texttt{" + tex_escape(Path(n).name) + r"}\,$=$\,\texttt{"
             + h + "}" for n, h in data["hashes"].items()]
    out.append("  SHA-256 (first 12 hex): " + ";\n  ".join(items) + ".}")
    (HERE / "adiabatic_slopes.tex").write_text("\n".join(out) + "\n")


# --------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------
def main(argv: list[str]) -> int:
    manifest_only = "--manifest" in argv
    check = "--check" in argv

    print("== manifest ==")
    missing = write_manifest()
    print(f"   {len(MANIFEST)} artefacts, {missing} missing "
          f"-> {rel(HERE / 'MANIFEST.tsv')}")
    if manifest_only:
        return 1 if missing else 0

    print("== adiabatic validation (one command, one dataset) ==")
    win = epsilon_window()
    print(f"   epsilon window: {win}")

    out_v, dt_v = run(VALIDATION)
    rows = parse_validation(out_v)
    print(f"   {VALIDATION.name}: {len(rows)} configurations, {dt_v:.0f}s")
    for r in rows:
        print(f"     {r['config'][:44]:44s} "
              f"leading {r['leading_slope']:.2f}+/-{r['leading_sigma']:.2f}  "
              f"exact {r['exact_slope']:.2f}+/-{r['exact_sigma']:.2f}")

    out_e, dt_e = run(EXACT)
    ex = parse_exact(out_e)
    print(f"   {EXACT.name}: slope {ex['slope']:.2f}"
          + (f" (robust {ex['robust_slope']:.2f})"
             if ex["robust_slope"] else "")
          + f", residual {ex['residual']:.2e} at eps={ex['residual_at']}"
          + f", {dt_e:.0f}s")

    sep = locus_separation()
    print(f"   fit interval r/M = {sep['fit_interval_r_over_M']}, "
          f"nearest excluded locus {sep['min_separation_r_over_M']:g} M away")

    hashes = {}
    for _, _, path in MANIFEST:
        p = ROOT / path
        if p.exists() and p.suffix == ".py" and "ThakurtaMetric" in path:
            hashes[path] = short(p)

    data = {
        "generated_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "epsilon_window": win,
        "validation": {"script": rel(VALIDATION), "rows": rows,
                       "seconds": round(dt_v, 1)},
        "exact": {"script": rel(EXACT), **ex, "seconds": round(dt_e, 1)},
        "loci": sep,
        "hashes": hashes,
    }
    (HERE / "adiabatic_slopes.json").write_text(json.dumps(data, indent=2) + "\n")
    write_tex(data)
    print(f"   wrote {rel(HERE / 'adiabatic_slopes.json')}")
    print(f"   wrote {rel(HERE / 'adiabatic_slopes.tex')}")

    sub = subwindow_drift()
    data["subwindow"] = sub
    (HERE / "adiabatic_slopes.json").write_text(json.dumps(data, indent=2) + "\n")
    write_tex(data)

    ok = report_subwindow(sub)
    return 1 if (missing or (check and not ok)) else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
