# -*- coding: utf-8 -*-


# This file was *autogenerated* from the file kerr_tau_Wij_naming3.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p0 = RealNumber('1.0'); _sage_const_0p9 = RealNumber('0.9'); _sage_const_2p5 = RealNumber('2.5'); _sage_const_1p4 = RealNumber('1.4'); _sage_const_1200 = Integer(1200); _sage_const_2300 = Integer(2300); _sage_const_11428 = Integer(11428); _sage_const_5519 = Integer(5519); _sage_const_24700 = Integer(24700); _sage_const_62500 = Integer(62500); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_100 = Integer(100); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_1 = Integer(1); _sage_const_12p0 = RealNumber('12.0'); _sage_const_200 = Integer(200); _sage_const_0 = Integer(0); _sage_const_1en6 = RealNumber('1e-6'); _sage_const_11p0 = RealNumber('11.0'); _sage_const_7p0 = RealNumber('7.0'); _sage_const_10p5 = RealNumber('10.5'); _sage_const_8p5 = RealNumber('8.5'); _sage_const_6p5 = RealNumber('6.5'); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_0p1 = RealNumber('0.1'); _sage_const_0p5 = RealNumber('0.5'); _sage_const_0p25 = RealNumber('0.25'); _sage_const_0p3 = RealNumber('0.3'); _sage_const_0p2 = RealNumber('0.2'); _sage_const_4000 = Integer(4000)# NAMING KLEINIANO v3: test decisivo. R_i = zeta_i(u(r)+C), C = offset di base
# (Baker basa a s=inf branch point; io ho u basata altrove -> costante C sul Jacobiano).
# zeta non e' invariante per traslazione: se ESISTE un unico C (2 complessi) con
#   d/dr zeta_i(u(r)+C) = dR_i/dr   per i=1,2 e tutti gli r  => R_i CHIUSO in zeta_i.
# Trovo C per minimizzazione, poi VERIFICO residuo su punti held-out.
from sage.all import QQ
from sage.schemes.riemann_surfaces.riemann_surface import RiemannSurface as SageRS
from abelfunctions import RiemannTheta
import numpy as np
from scipy.integrate import quad
from scipy.optimize import least_squares

M,a,J,Ehat = _sage_const_1p0 ,_sage_const_0p9 ,_sage_const_2p5 ,_sage_const_1p4 
Rs = PolynomialRing(QQ, ['s','Y']); s,Y = Rs.gens()
lam=[QQ(_sage_const_1200 ),QQ(-_sage_const_2300 ),QQ(-_sage_const_11428 ),QQ(-_sage_const_5519 ),QQ(_sage_const_24700 ),QQ(_sage_const_62500 )]
qpoly=sum(lam[i]*s**i for i in range(_sage_const_6 ))
X=SageRS(Y**_sage_const_2 -qpoly, prec=_sage_const_100 )
PM=np.array(X.period_matrix(),dtype=complex); tau=np.array(X.riemann_matrix(),dtype=complex)
dr1=(lam[_sage_const_3 ]*s+_sage_const_2 *lam[_sage_const_4 ]*s**_sage_const_2 +_sage_const_3 *lam[_sage_const_5 ]*s**_sage_const_3 )/_sage_const_2 ; dr2=lam[_sage_const_5 ]*s**_sage_const_2 /_sage_const_2 
MIV=np.array(X.matrix_of_integral_values([Rs(_sage_const_1 ),s,dr1,dr2]),dtype=complex)
om,eta=MIV[:_sage_const_2 ,:_sage_const_2 ],MIV[_sage_const_2 :,:_sage_const_2 ]; ominv=np.linalg.inv(om); kappa=eta@ominv
def qn(sv): return sum(float(lam[i])*sv**i for i in range(_sage_const_6 ))
r0=_sage_const_12p0 ; s0=_sage_const_1p0 /r0
def u_unnorm(s_to):   # base a s0 (poi correggo con C)
    I0=quad(lambda t:_sage_const_1p0 /(_sage_const_2 *np.sqrt(qn(t))),s0,s_to,limit=_sage_const_200 )[_sage_const_0 ]
    I1=quad(lambda t:t/(_sage_const_2 *np.sqrt(qn(t))),s0,s_to,limit=_sage_const_200 )[_sage_const_0 ]
    return np.array([I0,I1],dtype=complex)
def zeta_klein(v):   # v = u + C (arg completo); zeta_i=-(kappa (v-?))... uso forma theta pura:
    # zeta_i(v) = -(kappa v)_i + (ominv^T grad_z log theta(ominv v))_i   [caratteristica 0]
    zn=ominv@v; th=complex(RiemannTheta(zn,tau))
    g=np.array([complex(RiemannTheta(zn,tau,derivs=[e])) for e in ([_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ])])
    return -(kappa@v)+(ominv.T@(g/th))
def dRi_dr(i,rv):
    sv=_sage_const_1p0 /rv; Y_=np.sqrt(qn(sv)); dsdr=-_sage_const_1p0 /rv**_sage_const_2 
    Nd=[(lam[_sage_const_3 ]*sv+_sage_const_2 *lam[_sage_const_4 ]*sv**_sage_const_2 +_sage_const_3 *lam[_sage_const_5 ]*sv**_sage_const_3 )/_sage_const_4 ,(lam[_sage_const_5 ]*sv**_sage_const_2 )/_sage_const_4 ]
    return Nd[i]/Y_*dsdr
def dzeta_dr(rv,C):
    h=_sage_const_1en6 
    vp=u_unnorm(_sage_const_1p0 /(rv+h))+C; vm=u_unnorm(_sage_const_1p0 /(rv-h))+C
    return (zeta_klein(vp)-zeta_klein(vm))/(_sage_const_2 *h)

rg_fit=np.linspace(_sage_const_11p0 ,_sage_const_7p0 ,_sage_const_5 ); rg_test=np.array([_sage_const_10p5 ,_sage_const_8p5 ,_sage_const_6p5 ])
DRfit=np.array([[dRi_dr(_sage_const_0 ,rv),dRi_dr(_sage_const_1 ,rv)] for rv in rg_fit])
def resid(Cr):
    C=np.array([Cr[_sage_const_0 ]+_sage_const_1j *Cr[_sage_const_1 ],Cr[_sage_const_2 ]+_sage_const_1j *Cr[_sage_const_3 ]])
    out=[]
    for k,rv in enumerate(rg_fit):
        dz=dzeta_dr(rv,C)
        for i in range(_sage_const_2 ):
            d=dz[i]-DRfit[k,i]; out+=[d.real,d.imag]
    return out
print("cerco C (offset base Jacobiano) t.c. dzeta_i(u+C)/dr = dR_i/dr ...")
best=None
for C0 in [ [_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0p1 ,_sage_const_0p1 ,_sage_const_0p1 ,_sage_const_0p1 ],[_sage_const_0p5 ,_sage_const_0 ,_sage_const_0p5 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0p5 ,_sage_const_0 ,_sage_const_0p5 ],
            [_sage_const_0p25 ,_sage_const_0p25 ,-_sage_const_0p25 ,_sage_const_0p25 ],[-_sage_const_0p3 ,_sage_const_0p2 ,_sage_const_0p3 ,-_sage_const_0p2 ] ]:
    sol=least_squares(resid,C0,method='lm',max_nfev=_sage_const_4000 )
    if best is None or sol.cost<best.cost: best=sol
C=np.array([best.x[_sage_const_0 ]+_sage_const_1j *best.x[_sage_const_1 ],best.x[_sage_const_2 ]+_sage_const_1j *best.x[_sage_const_3 ]])
print("C =",np.round(C,_sage_const_5 ),"  costo fit =",best.cost)
# VERIFICA su punti held-out
print("\n=== VERIFICA held-out: dzeta_i(u+C)/dr vs dR_i/dr ===")
mx=_sage_const_0 
for rv in rg_test:
    dz=dzeta_dr(rv,C); dR=np.array([dRi_dr(_sage_const_0 ,rv),dRi_dr(_sage_const_1 ,rv)])
    e=np.max(np.abs(dz-dR)); mx=max(mx,e)
    print(f"  r={rv}: dzeta={np.round(dz,_sage_const_5 )}  dR={np.round(dR,_sage_const_5 )}  |diff|={e:.2e}")
print(f"\nMAX held-out diff = {mx:.2e}")
print("=> se ~1e-6: R_i = zeta_i(u+C) CONFERMATO (naming Baker, C=offset base). Naming CHIUSO.")
print("   (se no: la 2a specie NON e' bare zeta_i -> serve forma-differenza agli e_pm).")

