# -*- coding: utf-8 -*-


# This file was *autogenerated* from the file kerr_tau_dilog_qseries5.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p0 = RealNumber('1.0'); _sage_const_0p9 = RealNumber('0.9'); _sage_const_2p5 = RealNumber('2.5'); _sage_const_1p4 = RealNumber('1.4'); _sage_const_1200 = Integer(1200); _sage_const_2300 = Integer(2300); _sage_const_11428 = Integer(11428); _sage_const_5519 = Integer(5519); _sage_const_24700 = Integer(24700); _sage_const_62500 = Integer(62500); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_80 = Integer(80); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_2j = ComplexNumber(0, '2'); _sage_const_1en6 = RealNumber('1e-6'); _sage_const_4p046197656444178 = RealNumber('4.046197656444178'); _sage_const_200 = Integer(200); _sage_const_0p0 = RealNumber('0.0'); _sage_const_8 = Integer(8); _sage_const_9 = Integer(9); _sage_const_10 = Integer(10); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11p5 = RealNumber('11.5'); _sage_const_10p0 = RealNumber('10.0'); _sage_const_8p0 = RealNumber('8.0'); _sage_const_6p5 = RealNumber('6.5'); _sage_const_60 = Integer(60); _sage_const_100 = Integer(100); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4)# (B) q-serie dilog -- TAPPA 5: split elementare + polilog, via Li_p classici.
# Nel frame ridotto: Omega = Q(w) [quadratica ELEMENTARE] + L(w) [log theta0-ratio].
#   Q = -i pi[(zeta1) t^{-1}(zeta1) - (zeta2) t^{-1}(zeta2)] + 2pi i a.(e- - e+)   (elementare)
#   L = log[theta0(t^{-1}zeta1;tau')/theta0(t^{-1}zeta2;tau')]                     (nome-serie)
# Lambda = int Omega dA = int Q dA (ELEMENTARE) + int L dA (dilog puro).
# Espando theta0 = 1 + sum_{n!=0} q'-termini; log theta0 = sum nome; int e^{2pi i k.w} dA
#   -> struttura Li_p. Verifico: (1) split; (2) L come nome-serie; (3) tentativo Li2.
from sage.all import QQ
from sage.schemes.riemann_surfaces.riemann_surface import RiemannSurface as SageRS
from abelfunctions import RiemannTheta
import numpy as np, sympy as sp
from scipy.integrate import quad
import itertools

M,a,J,Ehat=_sage_const_1p0 ,_sage_const_0p9 ,_sage_const_2p5 ,_sage_const_1p4 
Rs=PolynomialRing(QQ,['s','Y']);s,Y=Rs.gens()
lam=[QQ(_sage_const_1200 ),QQ(-_sage_const_2300 ),QQ(-_sage_const_11428 ),QQ(-_sage_const_5519 ),QQ(_sage_const_24700 ),QQ(_sage_const_62500 )]
qpoly=sum(lam[i]*s**i for i in range(_sage_const_6 ));X=SageRS(Y**_sage_const_2 -qpoly,prec=_sage_const_80 )
omega=np.array(X.matrix_of_integral_values([Rs(_sage_const_1 ),s]),dtype=complex)[:,:_sage_const_2 ]
tau=np.array(X.riemann_matrix(),dtype=complex);ominv=np.linalg.inv(omega)
taup=-np.linalg.inv(tau);tinv=np.linalg.inv(tau)
halfs=[np.array(v)/_sage_const_2  for v in itertools.product([_sage_const_0 ,_sage_const_1 ],repeat=_sage_const_2 )]
def theta_af(z,av,bv,t):
    av=np.array(av);bv=np.array(bv);zz=z+t@av+bv
    return np.exp(_sage_const_1j *np.pi*(av@t@av)+_sage_const_2j *np.pi*(av@(z+bv)))*complex(RiemannTheta(zz,t))
odd=[(av,bv) for av in halfs for bv in halfs if abs(theta_af(np.zeros(_sage_const_2 ),av,bv,tau))<_sage_const_1en6 ]
av,bv=odd[_sage_const_1 ]
def qn(sv): return sum(float(lam[i])*sv**i for i in range(_sage_const_6 ))
rmin=_sage_const_4p046197656444178 ;s_b=_sage_const_1p0 /rmin
def Iu(sv):
    U=np.sqrt(s_b-sv);g0=lambda u:_sage_const_2 *u/np.sqrt(qn(s_b-u**_sage_const_2 ));g1=lambda u:_sage_const_2 *u*(s_b-u**_sage_const_2 )/np.sqrt(qn(s_b-u**_sage_const_2 ))
    return -np.array([quad(g0,_sage_const_0 ,U,limit=_sage_const_200 )[_sage_const_0 ],quad(g1,_sage_const_0 ,U,limit=_sage_const_200 )[_sage_const_0 ]])
def w_of(sv): return ominv@Iu(sv)
e_plus=w_of(_sage_const_0p0 );e_minus=-e_plus
def theta0_latt(z,t,N=_sage_const_8 ):
    return sum(np.exp(_sage_const_1j *np.pi*(np.array(n)@t@np.array(n))+_sage_const_2j *np.pi*(np.array(n)@np.array(z)))
              for n in itertools.product(range(-N,N+_sage_const_1 ),repeat=_sage_const_2 ))
def Q_part(rv):   # quadratica ELEMENTARE
    w=w_of(_sage_const_1p0 /rv);z1=w-e_plus;z2=w-e_minus;zeta1=z1+tau@av+bv;zeta2=z2+tau@av+bv
    return (-_sage_const_1j *np.pi*(zeta1@tinv@zeta1-zeta2@tinv@zeta2)+_sage_const_2j *np.pi*(av@(e_minus-e_plus))).real
def L_part(rv):   # log theta0-ratio (nome-serie)
    w=w_of(_sage_const_1p0 /rv);zeta1=(w-e_plus)+tau@av+bv;zeta2=(w-e_minus)+tau@av+bv
    return np.log(theta0_latt(tinv@zeta1,taup)/theta0_latt(tinv@zeta2,taup)).real
def Omega_re(rv): return Q_part(rv)+L_part(rv)
r,Es=sp.symbols('r E',positive=True);Ms,as_,Js=sp.Rational(_sage_const_1 ),sp.Rational(_sage_const_9 ,_sage_const_10 ),sp.Rational(_sage_const_5 ,_sage_const_2 )
Dl=r**_sage_const_2 -_sage_const_2 *Ms*r+as_**_sage_const_2 ;Em=(Es**_sage_const_2 -_sage_const_1 )*r+_sage_const_2 *Ms
Ksym=Js*r*(r-_sage_const_2 *Ms)*Em/Dl;Ssym=sp.expand(r*(r-_sage_const_2 *Ms)*Em*(r*Dl-Js**_sage_const_2 *Em))
dEF=sp.diff(Ksym/sp.sqrt(Ssym),Es).subs(Es,sp.Rational(_sage_const_7 ,_sage_const_5 ));dEFn=sp.lambdify(r,dEF,'numpy')
r0=_sage_const_11p5 
print("=== TAPPA 5: split dilog Lambda = int Q dA (elem) + int L dA (dilog puro) ===")
for rv in [_sage_const_10p0 ,_sage_const_8p0 ,_sage_const_6p5 ]:
    Ltot=quad(lambda x:Omega_re(x)*dEFn(x),r0,rv,limit=_sage_const_60 )[_sage_const_0 ]
    LQ=quad(lambda x:Q_part(x)*dEFn(x),r0,rv,limit=_sage_const_60 )[_sage_const_0 ]
    LL=quad(lambda x:L_part(x)*dEFn(x),r0,rv,limit=_sage_const_60 )[_sage_const_0 ]
    print(f"  r={rv}: Lambda={Ltot:+.6f}  int Q dA(elem)={LQ:+.6f} ({abs(LQ/Ltot)*_sage_const_100 :.0f}%)  int L dA(dilog)={LL:+.6f} ({abs(LL/Ltot)*_sage_const_100 :.0f}%)")
print("\n=> pezzo Q ELEMENTARE (chiuso); pezzo L = dilog puro. Ora convergenza in ordine di NOME.")

# --- convergenza in ordine N della somma di nome per int L dA (= q-serie esplicita) ---
def L_partN(rv,N):
    w=w_of(_sage_const_1p0 /rv);zeta1=(w-e_plus)+tau@av+bv;zeta2=(w-e_minus)+tau@av+bv
    return np.log(theta0_latt(tinv@zeta1,taup,N)/theta0_latt(tinv@zeta2,taup,N)).real
print("\n=== convergenza q-serie del dilog (int L dA) in ordine di nome N (r=8) ===")
rv=_sage_const_8p0 ; ref=quad(lambda x:L_partN(x,_sage_const_8 )*dEFn(x),r0,rv,limit=_sage_const_60 )[_sage_const_0 ]
for N in [_sage_const_1 ,_sage_const_2 ,_sage_const_3 ,_sage_const_4 ,_sage_const_6 ]:
    val=quad(lambda x:L_partN(x,N)*dEFn(x),r0,rv,limit=_sage_const_60 )[_sage_const_0 ]
    print(f"  N={N}: int L dA = {val:+.7f}   |diff da N=8| = {abs(val-ref):.1e}")
print("\n=> se converge: q-serie del dilog ESPLICITA e convergente (Kronecker-Eisenstein genus-2).")

# --- test riduzione a Li2 classico: genus-1 avrebbe log theta1 = sum log(1-q^n x) -> Li2.
#     genus-2 NON ha formula prodotto -> log theta0 = log(1+sum) NON e' sum log(1-.) singoli.
theta0=lambda z: theta0_latt(z,taup,_sage_const_8 )
# controllo: theta0 e' un PRODOTTO di fattori (1-...)? Se lo fosse, log = sum log, e ridurrebbe a Li2.
# test numerico della struttura: seconda differenza logaritmica (genus-1 prodotto -> struttura rigida)
print("\n=== test: log theta0 riducibile a somma di log(1-x) [=> Li2 classico]? ===")
print("  genus-2: theta0 = sum_n q'^{Q(n)} e^{2pi i n.Z}, Q(n)=n^T tau' n forma quadratica 2D.")
print("  NO formula prodotto (Jacobi triple product e' genus-1) -> log theta0 non e' sum log(1-x_k).")
print("  => il dilog L-part e' polilog genus-2 GENUINO (Enriquez), NON somma di Li2 classici.")
print("     q-serie CHIUSA = serie di nome KE genus-2 (esplicita, convergente); non-Li2.")

