# -*- coding: utf-8 -*-


# This file was *autogenerated* from the file kerr_quasiperiods_bel.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1200 = Integer(1200); _sage_const_2300 = Integer(2300); _sage_const_11428 = Integer(11428); _sage_const_5519 = Integer(5519); _sage_const_24700 = Integer(24700); _sage_const_62500 = Integer(62500); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_100 = Integer(100); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_1 = Integer(1); _sage_const_2j = ComplexNumber(0, '2')# Quasi-periodi di 2a specie (matrice eta / kappa di Klein) per la curva genus-2
# del ramo tau -> ingrediente MANCANTE per la forma chiusa Kleiniana di psi.
#
# psi = 1/2 Ehat (rho - rho~) e' un integrale iterato lunghezza-2 di forme di
# 1a/2a specie (NO 3a specie: provato beta_+=delta_+=0). Per la teoria classica
# Baker-Klein CHIUDE nelle funzioni Kleiniane zeta,sigma (peso 1, stessa classe
# di phi_0), NON e' un polilog. Serve la matrice dei quasi-periodi eta (2a specie).
#
# METODO (rompe il muro "Sage non da' eta" di doranTau.md sec.7-iii):
#   - modello DISPARI (quintica, 1 punto all'infinito) via x=1/s: le 2a-specie
#     s^2,s^3 ds/Y sono pulite (doppio polo, no residuo). Il modello PARI (deg 6)
#     ha 2 punti all'infinito -> x^2 dx/y e' 3a specie (residuo) -> eta sbagliato.
#   - 2a-specie CANONICHE di Baker-Enolski-Leykin (coeff della quintica):
#       dr_1 = (lam3 s + 2 lam4 s^2 + 3 lam5 s^3) ds/(4y)
#       dr_2 = lam5 s^2 ds/(4y)
#   - periodi via matrix_of_integral_values di Sage sui 4 cicli (INTERI: no crash
#     Singular). Pairing du=[1,s] <-> dr=[dr1,dr2].
#
# VALIDAZIONE: kappa=eta*omega^-1 SIMMETRICA (1.4e-12); Legendre generalizzata
#   omega' eta^T - omega eta'^T = -i pi I (canonica).
#
# Quintica: Y^2 = s^6 S(1/s), S_tau = 1200x^6-2300x^5-11428x^4-5519x^3+24700x^2
#   +62500x (params M=1,a=9/10,E=7/5,J=5/2). lam_i = coeff (interi).
from sage.all import QQ
from sage.schemes.riemann_surfaces.riemann_surface import RiemannSurface as SageRS
import numpy as np

Rs = PolynomialRing(QQ, ['s', 'Y']); s, Y = Rs.gens()
lam = [QQ(_sage_const_1200 ), QQ(-_sage_const_2300 ), QQ(-_sage_const_11428 ), QQ(-_sage_const_5519 ), QQ(_sage_const_24700 ), QQ(_sage_const_62500 )]  # i=0..5
q = sum(lam[i]*s**i for i in range(_sage_const_6 ))
X = SageRS(Y**_sage_const_2  - q, prec=_sage_const_100 )
assert X.genus == _sage_const_2 

# 2a-specie canoniche BEL (fattore /2 = 4y->2y della convenzione f_y)
dr1 = (lam[_sage_const_3 ]*s + _sage_const_2 *lam[_sage_const_4 ]*s**_sage_const_2  + _sage_const_3 *lam[_sage_const_5 ]*s**_sage_const_3 )/_sage_const_2 
dr2 = lam[_sage_const_5 ]*s**_sage_const_2 /_sage_const_2 
du = [Rs(_sage_const_1 ), s]                    # du_1=1, du_2=s
Pi = np.array(X.matrix_of_integral_values(du + [dr1, dr2]), dtype=complex)  # 4x4
omega, omega_p = Pi[:_sage_const_2 , :_sage_const_2 ], Pi[:_sage_const_2 , _sage_const_2 :]     # 1a specie a,b
eta,   eta_p   = Pi[_sage_const_2 :, :_sage_const_2 ], Pi[_sage_const_2 :, _sage_const_2 :]     # 2a specie a,b
tau = np.linalg.solve(omega, omega_p)
kappa = eta @ np.linalg.inv(omega)          # matrice di Klein (per sigma)
Leg = omega_p @ eta.T - omega @ eta_p.T

print('tau =\n', np.round(tau, _sage_const_5 ))
print('tau sym err        =', np.linalg.norm(tau - tau.T))
print('kappa =\n', np.round(kappa, _sage_const_5 ))
print('kappa SYM ERR      =', np.linalg.norm(kappa - kappa.T))
print('Legendre/(2 pi i)  =\n', np.round(Leg/(_sage_const_2j *np.pi), _sage_const_4 ), '  (atteso -I/2)')
print("\nOK: eta (2a specie) calcolata e validata -> sigma/zeta di Klein pronti.")
print("    Prossimo: sigma=exp(-1/2 u^T kappa u) theta(...), zeta_i=d_i log sigma,")
print("    psi(r) = combinazione chiusa di zeta(u(r)); validare vs psi numerico.")

