# -*- coding: utf-8 -*-


# This file was *autogenerated* from the file kerr_tau_Wij_naming.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p0 = RealNumber('1.0'); _sage_const_0p9 = RealNumber('0.9'); _sage_const_2p5 = RealNumber('2.5'); _sage_const_1p4 = RealNumber('1.4'); _sage_const_1200 = Integer(1200); _sage_const_2300 = Integer(2300); _sage_const_11428 = Integer(11428); _sage_const_5519 = Integer(5519); _sage_const_24700 = Integer(24700); _sage_const_62500 = Integer(62500); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_80 = Integer(80); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_1 = Integer(1); _sage_const_2j = ComplexNumber(0, '2'); _sage_const_12p0 = RealNumber('12.0'); _sage_const_200 = Integer(200); _sage_const_0 = Integer(0); _sage_const_11p0 = RealNumber('11.0'); _sage_const_6p0 = RealNumber('6.0'); _sage_const_7 = Integer(7); _sage_const_1en5 = RealNumber('1e-5'); _sage_const_0p0 = RealNumber('0.0'); _sage_const_1en30 = RealNumber('1e-30'); _sage_const_1en4 = RealNumber('1e-4'); _sage_const_1e6 = RealNumber('1e6')# NAMING KLEINIANO (TK tau, genus-2): i due integrali abeliani canonici della
# chiusura W_ij SONO le funzioni tabulate di Baker.
#   R_i = int dr_i (2a specie BEL)      -> zeta_i(u) Kleiniano (differenziale)
#   L   = int ds/(s Y) (3a specie)      -> log[sigma(u-e+)/sigma(u-e-)]
# Verifica a livello DIFFERENZIALE (robusto): d/dr(funz. Kleiniana) = differenziale canonico.
# Modello dispari (quintica), params M=1,a=9/10,E=7/5,J=5/2 (stessi di Bel/thirdkind).
from sage.all import QQ
from sage.schemes.riemann_surfaces.riemann_surface import RiemannSurface as SageRS
from abelfunctions import RiemannTheta
import numpy as np
from scipy.integrate import quad
import itertools

M,a,J,Ehat = _sage_const_1p0 ,_sage_const_0p9 ,_sage_const_2p5 ,_sage_const_1p4 
Rs = PolynomialRing(QQ, ['s','Y']); s,Y = Rs.gens()
lam=[QQ(_sage_const_1200 ),QQ(-_sage_const_2300 ),QQ(-_sage_const_11428 ),QQ(-_sage_const_5519 ),QQ(_sage_const_24700 ),QQ(_sage_const_62500 )]
qpoly=sum(lam[i]*s**i for i in range(_sage_const_6 ))
X=SageRS(Y**_sage_const_2 -qpoly, prec=_sage_const_80 )
# periodi 1a specie (a,b) + 2a specie (BEL) -> omega, tau, kappa
dr1=(lam[_sage_const_3 ]*s+_sage_const_2 *lam[_sage_const_4 ]*s**_sage_const_2 +_sage_const_3 *lam[_sage_const_5 ]*s**_sage_const_3 )/_sage_const_2 ; dr2=lam[_sage_const_5 ]*s**_sage_const_2 /_sage_const_2 
Pi=np.array(X.matrix_of_integral_values([Rs(_sage_const_1 ),s,dr1,dr2]),dtype=complex)
omega,omega_p = Pi[:_sage_const_2 ,:_sage_const_2 ],Pi[:_sage_const_2 ,_sage_const_2 :]  # WRONG slice? Pi is 4x4: rows=diff, cols=cycles
# matrix_of_integral_values: righe=differenziali [du1,du2,dr1,dr2], colonne=4 cicli (a1,a2,b1,b2)
om=Pi[:_sage_const_2 ,:_sage_const_2 ]; omp=Pi[:_sage_const_2 ,_sage_const_2 :]; eta=Pi[_sage_const_2 :,:_sage_const_2 ]; etap=Pi[_sage_const_2 :,_sage_const_2 :]
tau=np.linalg.solve(om,omp); ominv=np.linalg.inv(om); kappa=eta@ominv
print("tau sym err=",np.linalg.norm(tau-tau.T)," kappa sym err=",np.linalg.norm(kappa-kappa.T))
Leg=omp@eta.T-om@etap.T; print("Legendre/(2pi i)=\n",np.round(Leg/(_sage_const_2j *np.pi),_sage_const_3 )," (canonica -I/2)")

def qn(sv): return sum(float(lam[i])*sv**i for i in range(_sage_const_6 ))
r0=_sage_const_12p0 ; s0=_sage_const_1p0 /r0
def Sn(rv):
    Dl=rv**_sage_const_2 -_sage_const_2 *M*rv+a**_sage_const_2 ; Emu=(Ehat**_sage_const_2 -_sage_const_1 )*rv+_sage_const_2 *M
    return rv*(rv-_sage_const_2 *M)*Emu*(rv*Dl-J**_sage_const_2 *Emu)
# Abel map UNnormalizzata u(r)=int_{s0}^{s}(1,t)/(2 sqrt q) dt (misura /2 = convenzione Leg -I/2)
def u_unnorm(sv):
    I0=quad(lambda t:_sage_const_1p0 /(_sage_const_2 *np.sqrt(qn(t))),s0,sv,limit=_sage_const_200 )[_sage_const_0 ]
    I1=quad(lambda t:t/(_sage_const_2 *np.sqrt(qn(t))),s0,sv,limit=_sage_const_200 )[_sage_const_0 ]
    return np.array([I0,I1],dtype=complex)
def zval(sv): return u_unnorm(sv)                      # u (Kleinian arg, unnormalizzato)

# zeta_i(u) = -(kappa u)_i + (omega^{-T} grad_z log theta[delta](omega^{-1} u))_i
halfs=[np.array(v)/_sage_const_2  for v in itertools.product([_sage_const_0 ,_sage_const_1 ],repeat=_sage_const_2 )]
chars=[(av,bv) for av in halfs for bv in halfs]
def logtheta_grad(zz, av, bv):   # grad_z log theta[av,bv](zz)
    z2=zz+tau@av+bv
    th=complex(RiemannTheta(z2,tau))
    g=np.array([complex(RiemannTheta(z2,tau,derivs=[e])) for e in ([_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ])])
    return _sage_const_2j *np.pi*av + g/th
def zeta_klein(u, av, bv):
    zn=ominv@u
    return -(kappa@u) + (ominv.T @ logtheta_grad(zn,av,bv))

# --- differenziale canonico dR_i/dr (BEL 2a specie) e du_i/dr ---
def dRi_dr(i,rv):   # dr_i in r: Ndr_i(s)/Y * ds/dr,  ds/dr=-1/r^2
    sv=_sage_const_1p0 /rv; Y_=np.sqrt(qn(sv)); dsdr=-_sage_const_1p0 /rv**_sage_const_2 
    Nd=[(lam[_sage_const_3 ]*sv+_sage_const_2 *lam[_sage_const_4 ]*sv**_sage_const_2 +_sage_const_3 *lam[_sage_const_5 ]*sv**_sage_const_3 )/_sage_const_4 ,(lam[_sage_const_5 ]*sv**_sage_const_2 )/_sage_const_4 ]  # BEL numeratori /4
    return Nd[i]/Y_*dsdr
def duidr(i,rv):
    sv=_sage_const_1p0 /rv; Y_=np.sqrt(qn(sv)); dsdr=-_sage_const_1p0 /rv**_sage_const_2 
    return (_sage_const_1p0  if i==_sage_const_0  else sv)/(_sage_const_2 *np.sqrt(qn(sv)))*dsdr   # /2 convenzione
# dzeta_i/dr = grad_u zeta_i . du/dr ; numerico via diff finita in r su zeta_klein
print("\n=== NAMING R_i = zeta_i(u): scan 16 caratteristiche, lstsq dzeta_i = A dR + C du ===")
rg2=np.linspace(_sage_const_11p0 ,_sage_const_6p0 ,_sage_const_7 )
DRr=np.array([[dRi_dr(_sage_const_0 ,rv),dRi_dr(_sage_const_1 ,rv)] for rv in rg2])
DUr=np.array([[duidr(_sage_const_0 ,rv),duidr(_sage_const_1 ,rv)] for rv in rg2])
Xdes=np.hstack([DRr,DUr])
best=None
for ci,(av,bv) in enumerate(chars):
    DZ=[]
    ok=True
    for rv in rg2:
        h=_sage_const_1en5 
        try:
            dz=(zeta_klein(zval(_sage_const_1p0 /(rv+h)),av,bv)-zeta_klein(zval(_sage_const_1p0 /(rv-h)),av,bv))/(_sage_const_2 *h)
        except Exception: ok=False; break
        DZ.append(dz)
    if not ok: continue
    DZ=np.array(DZ)
    tot=_sage_const_0p0 ; coefs=[]
    for i in range(_sage_const_2 ):
        coef,_,_,_=np.linalg.lstsq(Xdes,DZ[:,i],rcond=None)
        rr=float(np.max(np.abs(Xdes@coef-DZ[:,i]))/max(np.max(np.abs(DZ[:,i])),_sage_const_1en30 ))
        tot=max(tot,rr); coefs.append(coef)
    cleanness=float(sum(abs(c[_sage_const_2 ])+abs(c[_sage_const_3 ]) for c in coefs))  # |du coeff| piccolo = pulito
    score=cleanness if tot<_sage_const_1en4  else _sage_const_1e6 +tot                  # residuo basso prima, poi pulizia
    if best is None or score<best[_sage_const_0 ]:
        best=(score,ci,av,bv,coefs,tot)
_,ci,av,bv,coefs,tot=best
print(f"  MIGLIORE char #{ci} a={av} b={bv}  (residuo lstsq max={tot:.2e})")
for i in range(_sage_const_2 ):
    c=coefs[i]
    print(f"   zeta_{i+_sage_const_1 }: {c[_sage_const_0 ]:+.4f} dR1 {c[_sage_const_1 ]:+.4f} dR2 {c[_sage_const_2 ]:+.4f} du1 {c[_sage_const_3 ]:+.4f} du2")
print("=> Baker: atteso dzeta_i = dR_i (identita' su dR, du piccoli/interi). Se residuo~0 e coeff")
print("   semplici: R_i CHIUSO in zeta_i (funzione tabulata). Se coeff sporchi: convenzione ancora off.")

