# -*- coding: utf-8 -*-


# This file was *autogenerated* from the file kerr_psi_forward_abel.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_9 = Integer(9); _sage_const_10 = Integer(10); _sage_const_7 = Integer(7); _sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_1p0 = RealNumber('1.0'); _sage_const_0p9 = RealNumber('0.9'); _sage_const_1p4 = RealNumber('1.4'); _sage_const_2p5 = RealNumber('2.5'); _sage_const_1250 = Integer(1250); _sage_const_80 = Integer(80); _sage_const_2p0 = RealNumber('2.0'); _sage_const_12p0 = RealNumber('12.0'); _sage_const_4p046197656444178 = RealNumber('4.046197656444178'); _sage_const_200 = Integer(200); _sage_const_0 = Integer(0); _sage_const_10p0 = RealNumber('10.0'); _sage_const_8p0 = RealNumber('8.0'); _sage_const_6p0 = RealNumber('6.0'); _sage_const_5p0 = RealNumber('5.0'); _sage_const_4p3 = RealNumber('4.3')# MATTONE livello 3 (corretto): Abel map IN AVANTI u(r) sulla sestica tau +
# theta(u(r)) con derivate (ingredienti kernel polilog genus-2 per psi).
#
# Toolchain ROBUSTO (aggira il bug Singular di abelfunctions.integralbasis):
#   - periodi tau, A|B  -> RiemannSurface di Sage (base coomologia (1,x))
#   - Abel map u(r)     -> integrazione diretta di (1,x)/(2 sqrt(S)) (conv. f_y=2y)
#                          normalizzata: u = A^{-1} I(r)
#   - theta + derivate  -> RiemannTheta di abelfunctions (numpy, ogni tau)
# psi(r)=1/2 Ehat (rho-rho~) diventa polilog genus-2 nella coordinata u(r).
# Params RAZIONALI: M=1, a=9/10, E=7/5, J=5/2 (scattering, orbita reale r>=r_min).
from sage.all import QQ
from sage.schemes.riemann_surfaces.riemann_surface import RiemannSurface as SageRS
from abelfunctions import RiemannTheta
import numpy as np
from scipy.integrate import quad

M, a, E, J = QQ(_sage_const_1 ), QQ(_sage_const_9 )/_sage_const_10 , QQ(_sage_const_7 )/_sage_const_5 , QQ(_sage_const_5 )/_sage_const_2 
Mf, af, Ef, Jf = _sage_const_1p0 , _sage_const_0p9 , _sage_const_1p4 , _sage_const_2p5 

Rr = PolynomialRing(QQ, ['x', 'y']); x, y = Rr.gens()
Dl = x**_sage_const_2  - _sage_const_2 *M*x + a**_sage_const_2 ; Emu = (E**_sage_const_2  - _sage_const_1 )*x + _sage_const_2 *M
Sint = (_sage_const_1250 *x*(x - _sage_const_2 *M)*Emu*(x*Dl - J**_sage_const_2 *Emu)).change_ring(QQ)   # modello intero
print('Sint =', Sint)

X = SageRS(y**_sage_const_2  - Sint, prec=_sage_const_80 )
tau = np.array(X.riemann_matrix(), dtype=complex)
PM = np.array(X.period_matrix(), dtype=complex)          # 2x4 = [A | B]
Amat, Bmat = PM[:, :_sage_const_2 ], PM[:, _sage_const_2 :]
print('genus =', X.genus, ' tau sym err =', np.linalg.norm(tau - tau.T))
print('||A^{-1}B - tau|| =', np.linalg.norm(np.linalg.solve(Amat, Bmat) - tau))

# sestica numerica (stesso modello intero) e differenziali (1,x)/(2 sqrt(Sint))
cS = [float(c) for c in Sint.polynomial(x).list()]      # coeff crescenti
def Snum(r): return sum(c*r**k for k, c in enumerate(cS))
def w0(r): return _sage_const_1p0 /(_sage_const_2p0 *np.sqrt(Snum(r)))            # dx/(2y)
def w1(r): return r/(_sage_const_2p0 *np.sqrt(Snum(r)))              # x dx/(2y)

r0 = _sage_const_12p0 
rmin = _sage_const_4p046197656444178                                 # turning (branch point)
def abel_unnorm(r):    # I(r)=int_{r0}^{r}(w0,w1)dx  (asse reale, S>0 su orbita)
    I0 = quad(w0, r0, r, limit=_sage_const_200 )[_sage_const_0 ]
    I1 = quad(w1, r0, r, limit=_sage_const_200 )[_sage_const_0 ]
    return np.array([I0, I1], dtype=complex)
def u_of_r(r):         # Abel map normalizzata
    return np.linalg.solve(Amat, abel_unnorm(r))

# theta e derivate lungo l'orbita
print("\n r      u1            u2           |theta|      |grad|       |Hess|")
for r in [_sage_const_12p0 , _sage_const_10p0 , _sage_const_8p0 , _sage_const_6p0 , _sage_const_5p0 , _sage_const_4p3 ]:
    u = u_of_r(r)
    th = complex(RiemannTheta(u, tau))
    g = [complex(RiemannTheta(u, tau, derivs=[e])) for e in ([_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ])]
    H = [[complex(RiemannTheta(u, tau, derivs=[p,q])) for q in ([_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ])]
         for p in ([_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ])]
    gn = np.linalg.norm(g); Hn = np.linalg.norm(np.array(H))
    print(f"{r:5.1f}  {u[_sage_const_0 ]:+.4f}  {u[_sage_const_1 ]:+.4f}  {abs(th):.4e}  {gn:.3e}  {Hn:.3e}")

print("\nOK: coordinata u(r) in avanti + theta/grad/Hess disponibili.")
print("=> ingredienti kernel Kronecker-Eisenstein genus-2 per psi(r) pronti.")
print("   (rho-rho~ = integrale iterato lunghezza-2 nelle 1-forme dEF, L; il")
print("    kernel g^(n)(u,tau) si costruisce da theta e derivate qui valutate.)")

