# -*- coding: utf-8 -*-


# This file was *autogenerated* from the file kerr_tau_Wij_diffform.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p0 = RealNumber('1.0'); _sage_const_0p9 = RealNumber('0.9'); _sage_const_2p5 = RealNumber('2.5'); _sage_const_1p4 = RealNumber('1.4'); _sage_const_1200 = Integer(1200); _sage_const_2300 = Integer(2300); _sage_const_11428 = Integer(11428); _sage_const_5519 = Integer(5519); _sage_const_24700 = Integer(24700); _sage_const_62500 = Integer(62500); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_80 = Integer(80); _sage_const_1 = Integer(1); _sage_const_4p046197656444178 = RealNumber('4.046197656444178'); _sage_const_0 = Integer(0); _sage_const_200 = Integer(200); _sage_const_0p0 = RealNumber('0.0'); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_2j = ComplexNumber(0, '2'); _sage_const_1en6 = RealNumber('1e-6'); _sage_const_11p5 = RealNumber('11.5'); _sage_const_0p4 = RealNumber('0.4'); _sage_const_22 = Integer(22); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_1en30 = RealNumber('1e-30'); _sage_const_1en2 = RealNumber('1e-2'); _sage_const_0p5 = RealNumber('0.5')# NAMING KLEINIANO forma-DIFFERENZA (TK tau, genus-2). Riuso la convenzione VALIDATA
# di kerr_thirdkind_theta_closed (delta dispari, e_pm=+-w(r=inf), base al branch point,
# misura 1/sqrt(q)). Nomino i differenziali canonici in r ai punti e_pm:
#   3a specie (U_2): D3 = [zeta_d(w-e+) - zeta_d(w-e-)] . dw/dr   (log theta-ratio)
#   2a specie (U_3,U_4): G_pm,k = [grad zeta_d(w-e_pm)]_k . dw/dr  (zeta shiftata)
# VERIFICA (differenziale, robusto al divisore-theta perche' argomenti SHIFTATI a e_pm):
#   r^k/sqrt(S) = sum coeff * {du1/dr,du2/dr, D3, G+_1,G+_2,G-_1,G-_2}  (residuo ~0).
from sage.all import QQ
from sage.schemes.riemann_surfaces.riemann_surface import RiemannSurface as SageRS
from abelfunctions import RiemannTheta
import numpy as np
from scipy.integrate import quad
import itertools

M,a,J,Ehat = _sage_const_1p0 ,_sage_const_0p9 ,_sage_const_2p5 ,_sage_const_1p4 
Rs = PolynomialRing(QQ, ['s','Y']); s,Y = Rs.gens()
lam=[QQ(_sage_const_1200 ),QQ(-_sage_const_2300 ),QQ(-_sage_const_11428 ),QQ(-_sage_const_5519 ),QQ(_sage_const_24700 ),QQ(_sage_const_62500 )]
qpoly=sum(lam[i]*s**i for i in range(_sage_const_6 ))
X=SageRS(Y**_sage_const_2 -qpoly, prec=_sage_const_80 )
omega=np.array(X.matrix_of_integral_values([Rs(_sage_const_1 ),s]),dtype=complex)[:,:_sage_const_2 ]
tau=np.array(X.riemann_matrix(),dtype=complex); ominv=np.linalg.inv(omega)
def qn(sv): return sum(float(lam[i])*sv**i for i in range(_sage_const_6 ))
rmin=_sage_const_4p046197656444178 ; s_b=_sage_const_1p0 /rmin
def Iu(s_to):
    U=np.sqrt(s_b-s_to)
    g0=lambda u:_sage_const_2 *u*_sage_const_1p0 /np.sqrt(qn(s_b-u**_sage_const_2 )); g1=lambda u:_sage_const_2 *u*(s_b-u**_sage_const_2 )/np.sqrt(qn(s_b-u**_sage_const_2 ))
    return -np.array([quad(g0,_sage_const_0 ,U,limit=_sage_const_200 )[_sage_const_0 ],quad(g1,_sage_const_0 ,U,limit=_sage_const_200 )[_sage_const_0 ]])
def w_of(s_to): return ominv@Iu(s_to)
e_plus=w_of(_sage_const_0p0 ); e_minus=-e_plus

# caratteristiche odd
def theta_d(z,av,bv,order=_sage_const_0 ):
    av=np.array(av); bv=np.array(bv); zz=z+tau@av+bv
    pref=np.exp(_sage_const_1j *np.pi*(av@tau@av)+_sage_const_2j *np.pi*(av@(z+bv)))
    th=complex(RiemannTheta(zz,tau))
    if order==_sage_const_0 : return pref*th
    g=np.array([complex(RiemannTheta(zz,tau,derivs=[e])) for e in ([_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ])])
    if order==_sage_const_1 : return _sage_const_2j *np.pi*av + g/th          # grad log theta[delta]
    H=np.array([[complex(RiemannTheta(zz,tau,derivs=[p,q])) for q in ([_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ])] for p in ([_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ])])
    return H/th - np.outer(g/th,g/th)                # Hess log theta[delta]
halfs=[np.array(v)/_sage_const_2  for v in itertools.product([_sage_const_0 ,_sage_const_1 ],repeat=_sage_const_2 )]
odd=[(av,bv) for av in halfs for bv in halfs if abs(theta_d(np.zeros(_sage_const_2 ),av,bv))<_sage_const_1en6 ]
print("odd chars:",len(odd))

def Sn(rv):
    Dl=rv**_sage_const_2 -_sage_const_2 *M*rv+a**_sage_const_2 ; Emu=(Ehat**_sage_const_2 -_sage_const_1 )*rv+_sage_const_2 *M
    return rv*(rv-_sage_const_2 *M)*Emu*(rv*Dl-J**_sage_const_2 *Emu)
rg=np.linspace(_sage_const_11p5 ,rmin+_sage_const_0p4 ,_sage_const_22 )
sr=_sage_const_1p0 /rg; dsdr=-_sage_const_1p0 /rg**_sage_const_2 
du1dr=(_sage_const_1 /np.sqrt(qn(sr)))*dsdr; du2dr=(sr/np.sqrt(qn(sr)))*dsdr
W=np.array([w_of(sv) for sv in sr]); dwdr=(ominv@np.vstack([du1dr,du2dr])).T
sqrtS=np.sqrt(Sn(rg))

print("\n delta  | k=2 resid | k=3 resid | k=4 resid  (r^k/sqrtS su base Kleiniana differenza)")
for di,(av,bv) in enumerate(odd):
    # colonne base ai punti r
    col_du1=du1dr; col_du2=du2dr
    D3=np.array([ (theta_d(W[i]-e_plus,av,bv,_sage_const_1 )-theta_d(W[i]-e_minus,av,bv,_sage_const_1 ))@dwdr[i] for i in range(len(rg))])
    Gp=np.array([ theta_d(W[i]-e_plus,av,bv,_sage_const_2 )@dwdr[i] for i in range(len(rg))])   # (N,2)
    Gm=np.array([ theta_d(W[i]-e_minus,av,bv,_sage_const_2 )@dwdr[i] for i in range(len(rg))])
    B=np.column_stack([col_du1,col_du2,D3,Gp[:,_sage_const_0 ],Gp[:,_sage_const_1 ],Gm[:,_sage_const_0 ],Gm[:,_sage_const_1 ]])
    resids=[]
    for k in [_sage_const_2 ,_sage_const_3 ,_sage_const_4 ]:
        target=rg**k/sqrtS
        coef,_,_,_=np.linalg.lstsq(B,target,rcond=None)
        resids.append(np.max(np.abs(B@coef-target))/max(np.max(np.abs(target)),_sage_const_1en30 ))
    if min(resids)<_sage_const_1en2  or di<_sage_const_2  or max(resids)<_sage_const_0p5 :
        print(f"  #{di} a={av} b={bv} | {resids[_sage_const_0 ]:.2e} | {resids[_sage_const_1 ]:.2e} | {resids[_sage_const_2 ]:.2e}")
print("\n=> se una delta da' residui ~0 per k=2,3,4: U_2,U_3,U_4 CHIUSI in forma-differenza")
print("   Kleiniana (theta[delta] dispari agli e_pm). Naming peso-1 robusto al divisore-theta.")

