# -*- coding: utf-8 -*-


# This file was *autogenerated* from the file kerr_tau_Wij_holomorphic.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p0 = RealNumber('1.0'); _sage_const_0p9 = RealNumber('0.9'); _sage_const_2p5 = RealNumber('2.5'); _sage_const_1p4 = RealNumber('1.4'); _sage_const_1200 = Integer(1200); _sage_const_2300 = Integer(2300); _sage_const_11428 = Integer(11428); _sage_const_5519 = Integer(5519); _sage_const_24700 = Integer(24700); _sage_const_62500 = Integer(62500); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_80 = Integer(80); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_2j = ComplexNumber(0, '2'); _sage_const_1en6 = RealNumber('1e-6'); _sage_const_4p046197656444178 = RealNumber('4.046197656444178'); _sage_const_200 = Integer(200); _sage_const_0p0 = RealNumber('0.0'); _sage_const_7 = Integer(7); _sage_const_5 = Integer(5); _sage_const_9 = Integer(9); _sage_const_10 = Integer(10); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_60p0 = RealNumber('60.0'); _sage_const_300 = Integer(300); _sage_const_1p96 = RealNumber('1.96'); _sage_const_0p81 = RealNumber('0.81'); _sage_const_6p25 = RealNumber('6.25'); _sage_const_50p = RealNumber('50.'); _sage_const_30p = RealNumber('30.'); _sage_const_20p = RealNumber('20.'); _sage_const_12p = RealNumber('12.'); _sage_const_8p = RealNumber('8.'); _sage_const_6p = RealNumber('6.'); _sage_const_5p = RealNumber('5.'); _sage_const_4p5 = RealNumber('4.5')# CHIUSURA parte OLOMORFA nella base canonica (TK tau, genus-2).
# Fisso i coeff di POLO ai g_i simbolici (parti principali); il residuo U_k-(polo) e'
# OLOMORFO -> risolvo i coeff di u1,u2 (+const) BEN CONDIZIONATO (non piu' fit degenere).
# Status atteso: come C0/Ce separatrice (principio a-periodi, no fit, dipendenti dai periodi).
from sage.all import QQ
from sage.schemes.riemann_surfaces.riemann_surface import RiemannSurface as SageRS
from abelfunctions import RiemannTheta
import numpy as np, sympy as sp
from scipy.integrate import quad
import itertools

M,a,J,Ehat = _sage_const_1p0 ,_sage_const_0p9 ,_sage_const_2p5 ,_sage_const_1p4 
Rs=PolynomialRing(QQ,['s','Y']); s,Y=Rs.gens()
lam=[QQ(_sage_const_1200 ),QQ(-_sage_const_2300 ),QQ(-_sage_const_11428 ),QQ(-_sage_const_5519 ),QQ(_sage_const_24700 ),QQ(_sage_const_62500 )]
qpoly=sum(lam[i]*s**i for i in range(_sage_const_6 )); X=SageRS(Y**_sage_const_2 -qpoly,prec=_sage_const_80 )
omega=np.array(X.matrix_of_integral_values([Rs(_sage_const_1 ),s]),dtype=complex)[:,:_sage_const_2 ]
tau=np.array(X.riemann_matrix(),dtype=complex); ominv=np.linalg.inv(omega)
def theta_d(z,av,bv,order=_sage_const_0 ):
    av=np.array(av);bv=np.array(bv);zz=z+tau@av+bv
    pref=np.exp(_sage_const_1j *np.pi*(av@tau@av)+_sage_const_2j *np.pi*(av@(z+bv)));th=complex(RiemannTheta(zz,tau))
    if order==_sage_const_0 : return pref*th
    g=np.array([complex(RiemannTheta(zz,tau,derivs=[e])) for e in ([_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ])])
    if order==_sage_const_1 : return _sage_const_2j *np.pi*av+g/th
    H=np.array([[complex(RiemannTheta(zz,tau,derivs=[p,q])) for q in ([_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ])] for p in([_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ])])
    return H/th-np.outer(g/th,g/th)
halfs=[np.array(v)/_sage_const_2  for v in itertools.product([_sage_const_0 ,_sage_const_1 ],repeat=_sage_const_2 )]
odd=[(av,bv) for av in halfs for bv in halfs if abs(theta_d(np.zeros(_sage_const_2 ),av,bv))<_sage_const_1en6 ]
av,bv=odd[_sage_const_1 ]
def qn(sv): return sum(float(lam[i])*sv**i for i in range(_sage_const_6 ))
rmin=_sage_const_4p046197656444178 ; s_b=_sage_const_1p0 /rmin
def Iu(sv):
    U=np.sqrt(s_b-sv);g0=lambda u:_sage_const_2 *u/np.sqrt(qn(s_b-u**_sage_const_2 ));g1=lambda u:_sage_const_2 *u*(s_b-u**_sage_const_2 )/np.sqrt(qn(s_b-u**_sage_const_2 ))
    return -np.array([quad(g0,_sage_const_0 ,U,limit=_sage_const_200 )[_sage_const_0 ],quad(g1,_sage_const_0 ,U,limit=_sage_const_200 )[_sage_const_0 ]])
def w_of(sv): return ominv@Iu(sv)
e_plus=w_of(_sage_const_0p0 ); e_minus=-e_plus
# g_i simbolici (parti principali)
Es=sp.Symbol('E'); E0=sp.Rational(_sage_const_7 ,_sage_const_5 )
q6=sp.Symbol('q6'); # ricostruisco g_i:
r_,ss=sp.symbols('r s'); Ms,as_,Js=sp.Rational(_sage_const_1 ),sp.Rational(_sage_const_9 ,_sage_const_10 ),sp.Rational(_sage_const_5 ,_sage_const_2 )
Dl=r_**_sage_const_2 -_sage_const_2 *Ms*r_+as_**_sage_const_2 ;Em=(Es**_sage_const_2 -_sage_const_1 )*r_+_sage_const_2 *Ms
Ssym=sp.expand(r_*(r_-_sage_const_2 *Ms)*Em*(r_*Dl-Js**_sage_const_2 *Em)); q6e=sp.expand(ss**_sage_const_6 *Ssym.subs(r_,_sage_const_1 /ss))
gser=sp.series(_sage_const_1 /sp.sqrt(q6e),ss,_sage_const_0 ,_sage_const_4 ).removeO(); gsym=[sp.simplify(gser.coeff(ss,i)) for i in range(_sage_const_3 )]
gv=[float(gsym[i].subs(Es,E0)) for i in range(_sage_const_3 )]
print("g_i (num) =",np.round(gv,_sage_const_5 ))
# named primitives
def Om(rv):   # 3a specie log theta-ratio (canonica: residuo 1 in s a e_+)
    w=w_of(_sage_const_1p0 /rv); return np.log(theta_d(w-e_plus,av,bv,_sage_const_0 )/theta_d(w-e_minus,av,bv,_sage_const_0 ))
def Zvec(rv): # zeta_delta agli e_pm (2a specie), 2-vettori
    w=w_of(_sage_const_1p0 /rv); return theta_d(w-e_plus,av,bv,_sage_const_1 ),theta_d(w-e_minus,av,bv,_sage_const_1 )
def Pvec(rv): # wp_delta agli e_pm (2a specie triplo), matrici 2x2
    w=w_of(_sage_const_1p0 /rv); return theta_d(w-e_plus,av,bv,_sage_const_2 ),theta_d(w-e_minus,av,bv,_sage_const_2 )
def uhol(rv):
    s_to=_sage_const_1p0 /rv
    I0=quad(lambda t:_sage_const_1p0 /np.sqrt(qn(t)),_sage_const_1p0 /_sage_const_60p0 ,s_to,limit=_sage_const_300 )[_sage_const_0 ]
    I1=quad(lambda t:t/np.sqrt(qn(t)),_sage_const_1p0 /_sage_const_60p0 ,s_to,limit=_sage_const_300 )[_sage_const_0 ]
    return np.array([I0,I1])
def Sn(x):
    E2=_sage_const_1p96 ; Dl=x**_sage_const_2 -_sage_const_2 *x+_sage_const_0p81 ; Emm=(E2-_sage_const_1 )*x+_sage_const_2 
    return x*(x-_sage_const_2 )*Emm*(x*Dl-_sage_const_6p25 *Emm)   # M=1,a=0.9,E=7/5,J=5/2
def Uk(k,rv): return quad(lambda x:x**k/np.sqrt(Sn(x)),_sage_const_60p0 ,rv,limit=_sage_const_300 )[_sage_const_0 ]
# --- normalizzazioni canoniche di Om,Z,P via U_2 (puro 3a specie) su range LARGO ---
# U_2 = A*Om + hol(u1,u2)+c.  Om ben separato (log-polo) da u1,u2 -> ben condizionato.
rg=np.array([_sage_const_50p ,_sage_const_30p ,_sage_const_20p ,_sage_const_12p ,_sage_const_8p ,_sage_const_6p ,_sage_const_5p ,_sage_const_4p5 ])
def build_and_solve(k, cols):
    Bcols=[];
    for rv in rg: Bcols.append([c(rv) for c in cols])
    B=np.array(Bcols,dtype=complex); y=np.array([Uk(k,rv) for rv in rg],dtype=complex)
    coef,_,_,_=np.linalg.lstsq(B,y,rcond=None)
    cond=np.linalg.cond(B); res=np.max(np.abs(B@coef-y))
    return coef,cond,res
# U_2: base {Om, u1, u2, 1}
c2=lambda rv:Om(rv); u1=lambda rv:uhol(rv)[_sage_const_0 ]; u2=lambda rv:uhol(rv)[_sage_const_1 ]; one=lambda rv:_sage_const_1p0 
coef2,cond2,res2=build_and_solve(_sage_const_2 ,[c2,u1,u2,one])
print(f"\nU_2 = A*Om + a*u1 + b*u2 + c : cond={cond2:.1e} res={res2:.1e}")
print(f"  A(Om)={coef2[_sage_const_0 ]:+.5f}  (atteso -g0={-gv[_sage_const_0 ]:+.5f})  a(u1)={coef2[_sage_const_1 ]:+.5f} b(u2)={coef2[_sage_const_2 ]:+.5f} c={coef2[_sage_const_3 ]:+.5f}")
print("=> se A ~ -g0 e cond piccola: parte OLOMORFA (a,b) determinata BEN CONDIZIONATA (no fit degenere).")
print("   a,b = coeff olomorfi: numerici (dipendono dai periodi) ma da principio, come C0/Ce separatrice.")

