# -*- coding: utf-8 -*-


# This file was *autogenerated* from the file kerr_tau_Wij_diffform_integral.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p0 = RealNumber('1.0'); _sage_const_0p9 = RealNumber('0.9'); _sage_const_2p5 = RealNumber('2.5'); _sage_const_1p4 = RealNumber('1.4'); _sage_const_1200 = Integer(1200); _sage_const_2300 = Integer(2300); _sage_const_11428 = Integer(11428); _sage_const_5519 = Integer(5519); _sage_const_24700 = Integer(24700); _sage_const_62500 = Integer(62500); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_80 = Integer(80); _sage_const_1 = Integer(1); _sage_const_4p046197656444178 = RealNumber('4.046197656444178'); _sage_const_0 = Integer(0); _sage_const_200 = Integer(200); _sage_const_0p0 = RealNumber('0.0'); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_2j = ComplexNumber(0, '2'); _sage_const_1en6 = RealNumber('1e-6'); _sage_const_11p5 = RealNumber('11.5'); _sage_const_0p4 = RealNumber('0.4'); _sage_const_22 = Integer(22); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_10p0 = RealNumber('10.0'); _sage_const_8p0 = RealNumber('8.0'); _sage_const_6p0 = RealNumber('6.0'); _sage_const_4p6 = RealNumber('4.6')# NAMING peso-1 a livello INTEGRALE (TK tau, genus-2): U_k = funzioni tabulate theta[delta]
# agli e_pm. Le primitive sono valutate DIRETTAMENTE (log theta-ratio, zeta_delta), non
# integrando le derivate -> verifica vera. Poi assemblo il clock eta=U3-2M U2 nominato.
#   U_k(r) = a_k u1 + b_k u2 + c_k L_rat + d_k Zp1 + e_k Zp2 + f_k Zm1 + g_k Zm2 + const
#   L_rat = log[theta[d](w-e+)/theta[d](w-e-)] (3a specie), Zpm = zeta_delta(w-e_pm) (2a).
from sage.all import QQ
from sage.schemes.riemann_surfaces.riemann_surface import RiemannSurface as SageRS
from abelfunctions import RiemannTheta
import numpy as np
from scipy.integrate import quad
import itertools

M,a,J,Ehat = _sage_const_1p0 ,_sage_const_0p9 ,_sage_const_2p5 ,_sage_const_1p4 
Rs = PolynomialRing(QQ, ['s','Y']); s,Y = Rs.gens()
lam=[QQ(_sage_const_1200 ),QQ(-_sage_const_2300 ),QQ(-_sage_const_11428 ),QQ(-_sage_const_5519 ),QQ(_sage_const_24700 ),QQ(_sage_const_62500 )]
qpoly=sum(lam[i]*s**i for i in range(_sage_const_6 ))
X=SageRS(Y**_sage_const_2 -qpoly, prec=_sage_const_80 )
omega=np.array(X.matrix_of_integral_values([Rs(_sage_const_1 ),s]),dtype=complex)[:,:_sage_const_2 ]
tau=np.array(X.riemann_matrix(),dtype=complex); ominv=np.linalg.inv(omega)
def qn(sv): return sum(float(lam[i])*sv**i for i in range(_sage_const_6 ))
rmin=_sage_const_4p046197656444178 ; s_b=_sage_const_1p0 /rmin
def Iu(s_to):
    U=np.sqrt(s_b-s_to)
    g0=lambda u:_sage_const_2 *u*_sage_const_1p0 /np.sqrt(qn(s_b-u**_sage_const_2 )); g1=lambda u:_sage_const_2 *u*(s_b-u**_sage_const_2 )/np.sqrt(qn(s_b-u**_sage_const_2 ))
    return -np.array([quad(g0,_sage_const_0 ,U,limit=_sage_const_200 )[_sage_const_0 ],quad(g1,_sage_const_0 ,U,limit=_sage_const_200 )[_sage_const_0 ]])
def w_of(s_to): return ominv@Iu(s_to)
e_plus=w_of(_sage_const_0p0 ); e_minus=-e_plus
def theta_d(z,av,bv,order=_sage_const_0 ):
    av=np.array(av); bv=np.array(bv); zz=z+tau@av+bv
    pref=np.exp(_sage_const_1j *np.pi*(av@tau@av)+_sage_const_2j *np.pi*(av@(z+bv))); th=complex(RiemannTheta(zz,tau))
    if order==_sage_const_0 : return pref*th
    g=np.array([complex(RiemannTheta(zz,tau,derivs=[e])) for e in ([_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ])])
    if order==_sage_const_1 : return _sage_const_2j *np.pi*av+g/th
    H=np.array([[complex(RiemannTheta(zz,tau,derivs=[p,q])) for q in ([_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ])] for p in ([_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ])])
    return H/th-np.outer(g/th,g/th)
halfs=[np.array(v)/_sage_const_2  for v in itertools.product([_sage_const_0 ,_sage_const_1 ],repeat=_sage_const_2 )]
odd=[(av,bv) for av in halfs for bv in halfs if abs(theta_d(np.zeros(_sage_const_2 ),av,bv))<_sage_const_1en6 ]
av,bv=odd[_sage_const_1 ]   # delta #1 (migliore)
print("uso delta #1 a=",av," b=",bv)

def Sn(rv):
    Dl=rv**_sage_const_2 -_sage_const_2 *M*rv+a**_sage_const_2 ; Emu=(Ehat**_sage_const_2 -_sage_const_1 )*rv+_sage_const_2 *M
    return rv*(rv-_sage_const_2 *M)*Emu*(rv*Dl-J**_sage_const_2 *Emu)
# --- (1) coefficienti dal DIFFERENZIALE: r^k/sqrtS = sum coeff * basis_diff ---
rg=np.linspace(_sage_const_11p5 ,rmin+_sage_const_0p4 ,_sage_const_22 ); sr=_sage_const_1p0 /rg; dsdr=-_sage_const_1p0 /rg**_sage_const_2 
du1dr=(_sage_const_1 /np.sqrt(qn(sr)))*dsdr; du2dr=(sr/np.sqrt(qn(sr)))*dsdr
W=np.array([w_of(sv) for sv in sr]); dwdr=(ominv@np.vstack([du1dr,du2dr])).T; sqrtS=np.sqrt(Sn(rg))
D3=np.array([ (theta_d(W[i]-e_plus,av,bv,_sage_const_1 )-theta_d(W[i]-e_minus,av,bv,_sage_const_1 ))@dwdr[i] for i in range(len(rg))])
Gp=np.array([ theta_d(W[i]-e_plus,av,bv,_sage_const_2 )@dwdr[i] for i in range(len(rg))])
Gm=np.array([ theta_d(W[i]-e_minus,av,bv,_sage_const_2 )@dwdr[i] for i in range(len(rg))])
Bdiff=np.column_stack([du1dr,du2dr,D3,Gp[:,_sage_const_0 ],Gp[:,_sage_const_1 ],Gm[:,_sage_const_0 ],Gm[:,_sage_const_1 ]])
coeffs={}
for k in [_sage_const_2 ,_sage_const_3 ,_sage_const_4 ]:
    coef,_,_,_=np.linalg.lstsq(Bdiff,rg**k/sqrtS,rcond=None)
    coeffs[k]=coef
    print(f"  k={k}: coeff(u1,u2,Lrat,Zp1,Zp2,Zm1,Zm2)=",np.round(coef,_sage_const_4 ))

# --- (2) PRIMITIVE nominate valutate DIRETTAMENTE (non integrando derivate) ---
def named_prims(rv):
    sv=_sage_const_1p0 /rv; w=w_of(sv)
    Lrat=np.log(theta_d(w-e_plus,av,bv,_sage_const_0 )/theta_d(w-e_minus,av,bv,_sage_const_0 ))
    Zp=theta_d(w-e_plus,av,bv,_sage_const_1 ); Zm=theta_d(w-e_minus,av,bv,_sage_const_1 )
    # u1,u2 (olomorfe) = integrale abeliano diretto (coordinate Jacobiane, "nominate" = Abel map)
    return w,Lrat,Zp,Zm
def u_hol(rv):  # (u1,u2) unnormalizzate base r0
    s_to=_sage_const_1p0 /rv
    I0=quad(lambda t:_sage_const_1p0 /np.sqrt(qn(t)),_sage_const_1p0 /_sage_const_11p5 ,s_to,limit=_sage_const_200 )[_sage_const_0 ]
    I1=quad(lambda t:t/np.sqrt(qn(t)),_sage_const_1p0 /_sage_const_11p5 ,s_to,limit=_sage_const_200 )[_sage_const_0 ]
    return np.array([I0,I1])
def named_vec(rv):   # vettore [u1,u2,Lrat,Zp1,Zp2,Zm1,Zm2]
    _,Lrat,Zp,Zm=named_prims(rv); uh=u_hol(rv)
    return np.array([uh[_sage_const_0 ],uh[_sage_const_1 ],Lrat,Zp[_sage_const_0 ],Zp[_sage_const_1 ],Zm[_sage_const_0 ],Zm[_sage_const_1 ]])
def Uk_direct(k,rv): return quad(lambda x:x**k/np.sqrt(Sn(x)),_sage_const_11p5 ,rv,limit=_sage_const_200 )[_sage_const_0 ]

r0=_sage_const_11p5 ; base=named_vec(r0)
print("\n=== VERIFICA INTEGRALE: U_k(r) = coeff . [named(r)-named(r0)]  (floor theta ~1e-4) ===")
rtest=[_sage_const_10p0 ,_sage_const_8p0 ,_sage_const_6p0 ,_sage_const_4p6 ]
for k in [_sage_const_2 ,_sage_const_3 ,_sage_const_4 ]:
    print(f"  k={k}:")
    for rv in rtest:
        rec=complex(coeffs[k]@(named_vec(rv)-base)).real
        dr=Uk_direct(k,rv); print(f"    r={rv}: U_k(named)={rec:+.6f}  U_k(dir)={dr:+.6f}  diff={abs(rec-dr):.1e}")
# --- (3) clock eta = U3 - 2M U2 nominato ---
print("\n=== clock eta = U3 - 2M U2 in forma nominata theta[delta] ===")
ceta=coeffs[_sage_const_3 ]-_sage_const_2 *M*coeffs[_sage_const_2 ]
print("  coeff eta (u1,u2,Lrat,Zp1,Zp2,Zm1,Zm2)=",np.round(ceta,_sage_const_4 ))
for rv in rtest:
    rec=complex(ceta@(named_vec(rv)-base)).real
    dr=Uk_direct(_sage_const_3 ,rv)-_sage_const_2 *M*Uk_direct(_sage_const_2 ,rv); print(f"    r={rv}: eta(named)={rec:+.6f} eta(dir)={dr:+.6f} diff={abs(rec-dr):.1e}")
print("\n=> se diff~1e-4: clock e U_k NOMINATI in theta[delta] agli e_pm (funzioni tabulate).")
print("   3a specie=log theta-ratio; 2a specie=zeta_delta. phi0 e clock CHIUSI. Coeff dal differenziale.")

