# -*- coding: utf-8 -*-


# This file was *autogenerated* from the file kerr_tau_Wij_naming2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p0 = RealNumber('1.0'); _sage_const_0p9 = RealNumber('0.9'); _sage_const_2p5 = RealNumber('2.5'); _sage_const_1p4 = RealNumber('1.4'); _sage_const_1200 = Integer(1200); _sage_const_2300 = Integer(2300); _sage_const_11428 = Integer(11428); _sage_const_5519 = Integer(5519); _sage_const_24700 = Integer(24700); _sage_const_62500 = Integer(62500); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_100 = Integer(100); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_1 = Integer(1); _sage_const_1en8 = RealNumber('1e-8'); _sage_const_0 = Integer(0); _sage_const_1en14 = RealNumber('1e-14'); _sage_const_200 = Integer(200); _sage_const_120 = Integer(120); _sage_const_2j = ComplexNumber(0, '2'); _sage_const_11p0 = RealNumber('11.0'); _sage_const_6p5 = RealNumber('6.5'); _sage_const_7 = Integer(7); _sage_const_1en5 = RealNumber('1e-5'); _sage_const_2en5 = RealNumber('2e-5'); _sage_const_1en30 = RealNumber('1e-30'); _sage_const_1en2 = RealNumber('1e-2')# NAMING KLEINIANO v2: costante di Riemann ESATTA + base al branch point.
# Fix rispetto a v1: (1) Abel map basata al branch point (sigma-canonica di Baker),
# (2) ordine cicli coerente con period_matrix, (3) caratteristica sigma = RiemannConstantVector.
# Verifica: d/dr zeta_i(u) = dR_i/dr (BEL 2a specie) -> R_i CHIUSO in zeta_i tabulato.
from sage.all import QQ
from sage.schemes.riemann_surfaces.riemann_surface import RiemannSurface as SageRS
from abelfunctions import RiemannTheta
import numpy as np
from scipy.integrate import quad

M,a,J,Ehat = _sage_const_1p0 ,_sage_const_0p9 ,_sage_const_2p5 ,_sage_const_1p4 
Rs = PolynomialRing(QQ, ['s','Y']); s,Y = Rs.gens()
lam=[QQ(_sage_const_1200 ),QQ(-_sage_const_2300 ),QQ(-_sage_const_11428 ),QQ(-_sage_const_5519 ),QQ(_sage_const_24700 ),QQ(_sage_const_62500 )]
qpoly=sum(lam[i]*s**i for i in range(_sage_const_6 ))
X=SageRS(Y**_sage_const_2 -qpoly, prec=_sage_const_100 )
# --- periodi: uso period_matrix (ordine [A|B] verificato in kerr_psi_forward_abel) ---
PM=np.array(X.period_matrix(),dtype=complex)   # 2x4 = [A|B]
Amat,Bmat=PM[:,:_sage_const_2 ],PM[:,_sage_const_2 :]
tau=np.array(X.riemann_matrix(),dtype=complex)
print("A^-1 B - tau =",np.linalg.norm(np.linalg.solve(Amat,Bmat)-tau))
# 2a specie eta: matrix_of_integral_values su [du1,du2,dr1,dr2]; VERIFICO che il blocco
# olomorfo coincida con period_matrix (stesso ordine cicli).
dr1=(lam[_sage_const_3 ]*s+_sage_const_2 *lam[_sage_const_4 ]*s**_sage_const_2 +_sage_const_3 *lam[_sage_const_5 ]*s**_sage_const_3 )/_sage_const_2 ; dr2=lam[_sage_const_5 ]*s**_sage_const_2 /_sage_const_2 
MIV=np.array(X.matrix_of_integral_values([Rs(_sage_const_1 ),s,dr1,dr2]),dtype=complex)  # 4x4 (diff x cicli)
print("blocco olo MIV[:2] vs [A|B]:",np.linalg.norm(MIV[:_sage_const_2 ]-PM))  # se ~0 stesso ordine
om,omp=MIV[:_sage_const_2 ,:_sage_const_2 ],MIV[:_sage_const_2 ,_sage_const_2 :]; eta,etap=MIV[_sage_const_2 :,:_sage_const_2 ],MIV[_sage_const_2 :,_sage_const_2 :]
ominv=np.linalg.inv(om); kappa=eta@ominv
print("kappa sym err=",np.linalg.norm(kappa-kappa.T))

def qn(sv): return sum(float(lam[i])*sv**i for i in range(_sage_const_6 ))
# branch point base: radice reale piu' piccola di q (turning in s = 1/r_min)
qroots=np.roots([float(lam[i]) for i in range(_sage_const_5 ,-_sage_const_1 ,-_sage_const_1 )])
sb=float(min([z.real for z in qroots if abs(z.imag)<_sage_const_1en8  and z.real>_sage_const_0 ]))
print("branch point base s_b=",sb," (r_min=",_sage_const_1 /sb,")")
# Abel map UNnormalizzata basata a s_b: u(s)=int_{s_b}^{s}(1,t)/(2 sqrt q) dt
# regolarizzo la radice al branch point s=s_b - w^2
def u_unnorm(s_to):
    if abs(s_to-sb)<_sage_const_1en14 : return np.zeros(_sage_const_2 ,dtype=complex)
    W=np.sqrt(abs(sb-s_to))
    g0=lambda w: _sage_const_2 *w/(_sage_const_2 *np.sqrt(abs(qn(sb-w**_sage_const_2 ))))
    g1=lambda w: _sage_const_2 *w*(sb-w**_sage_const_2 )/(_sage_const_2 *np.sqrt(abs(qn(sb-w**_sage_const_2 ))))
    I0=quad(g0,_sage_const_0 ,W,limit=_sage_const_200 )[_sage_const_0 ]; I1=quad(g1,_sage_const_0 ,W,limit=_sage_const_200 )[_sage_const_0 ]
    sgn=-_sage_const_1p0  if s_to<sb else _sage_const_1p0 
    return sgn*np.array([I0,I1],dtype=complex)   # int_{s_b}^{s_to}

# costante di Riemann (sigma-canonica). Provo abelfunctions RiemannConstantVector; se crasha,
# uso la caratteristica half-integer per hyperell. odd (Delta = somma Abel di g branch points).
delta=None
try:
    from abelfunctions import RiemannSurface as ARS, RiemannConstantVector
    fA=Y**_sage_const_2 -qpoly
    Xa=ARS(fA)
    P0=Xa(sb, _sage_const_0 )     # branch point
    K=np.array(RiemannConstantVector(P0),dtype=complex)
    print("RiemannConstantVector K=",np.round(K,_sage_const_4 ))
    delta=('vec',K)
except Exception as ex:
    print("RiemannConstantVector fallito:",repr(ex)[:_sage_const_120 ])
    print("-> uso scan half-integer come fallback")

def logtheta_grad(zz, av, bv):
    z2=zz+tau@av+bv; th=complex(RiemannTheta(z2,tau))
    g=np.array([complex(RiemannTheta(z2,tau,derivs=[e])) for e in ([_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ])])
    return _sage_const_2j *np.pi*av + g/th
def zeta_klein_char(u, av, bv):
    zn=ominv@u; return -(kappa@u)+(ominv.T@logtheta_grad(zn,av,bv))
def zeta_klein_vecK(u, K):
    # theta con shift continuo K (RCV): log theta(ominv u + K); grad rispetto a u
    zn=ominv@u + K
    th=complex(RiemannTheta(zn,tau))
    g=np.array([complex(RiemannTheta(zn,tau,derivs=[e])) for e in ([_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ])])
    return -(kappa@u)+(ominv.T@(g/th))

def dRi_dr(i,rv):
    sv=_sage_const_1p0 /rv; Y_=np.sqrt(qn(sv)); dsdr=-_sage_const_1p0 /rv**_sage_const_2 
    Nd=[(lam[_sage_const_3 ]*sv+_sage_const_2 *lam[_sage_const_4 ]*sv**_sage_const_2 +_sage_const_3 *lam[_sage_const_5 ]*sv**_sage_const_3 )/_sage_const_4 ,(lam[_sage_const_5 ]*sv**_sage_const_2 )/_sage_const_4 ]
    return Nd[i]/Y_*dsdr
def zeta_of_r(rv, spec):
    u=u_unnorm(_sage_const_1p0 /rv)
    if spec[_sage_const_0 ]=='vec': return zeta_klein_vecK(u,spec[_sage_const_1 ])
    return zeta_klein_char(u,spec[_sage_const_1 ][_sage_const_0 ],spec[_sage_const_1 ][_sage_const_1 ])

import itertools
halfs=[np.array(v)/_sage_const_2  for v in itertools.product([_sage_const_0 ,_sage_const_1 ],repeat=_sage_const_2 )]
chars=[('char',(av,bv)) for av in halfs for bv in halfs]
specs=([delta] if delta else [])+chars
rg2=np.linspace(_sage_const_11p0 ,_sage_const_6p5 ,_sage_const_7 )
DR=np.array([[dRi_dr(_sage_const_0 ,rv),dRi_dr(_sage_const_1 ,rv)] for rv in rg2])
print("\n=== verifica d zeta_i/dr vs dR_i/dr (Baker: atteso identita') ===")
best=None
for spec in specs:
    try:
        DZ=np.array([ (zeta_of_r(rv+_sage_const_1en5 ,spec)-zeta_of_r(rv-_sage_const_1en5 ,spec))/(_sage_const_2en5 ) for rv in rg2])
    except Exception: continue
    # confronto diretto DZ vs DR (naming zeta_i = +/- R_i): residuo relativo
    em=min(np.max(np.abs(DZ-DR)),np.max(np.abs(DZ+DR)))/max(np.max(np.abs(DR)),_sage_const_1en30 )
    lbl='RCV' if spec[_sage_const_0 ]=='vec' else f"char a={spec[_sage_const_1 ][_sage_const_0 ]} b={spec[_sage_const_1 ][_sage_const_1 ]}"
    if best is None or em<best[_sage_const_0 ]: best=(em,lbl,DZ)
    if spec[_sage_const_0 ]=='vec' or em<_sage_const_1en2 : print(f"  {lbl}: |dzeta -/+ dR|_rel = {em:.2e}")
print(f"\nMIGLIORE: {best[_sage_const_1 ]}  residuo diretto = {best[_sage_const_0 ]:.2e}")
print("  DZ[0] vs DR[0]:",np.round(best[_sage_const_2 ][_sage_const_0 ],_sage_const_4 ),"  vs",np.round(DR[_sage_const_0 ],_sage_const_4 ))
print("=> se ~0: R_i = zeta_i(u) DIRETTO (naming Baker, funzione tabulata). ")

