# -*- coding: utf-8 -*-


# This file was *autogenerated* from the file kerr_tau_dilog_qseries1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p0 = RealNumber('1.0'); _sage_const_0p9 = RealNumber('0.9'); _sage_const_2p5 = RealNumber('2.5'); _sage_const_1p4 = RealNumber('1.4'); _sage_const_1200 = Integer(1200); _sage_const_2300 = Integer(2300); _sage_const_11428 = Integer(11428); _sage_const_5519 = Integer(5519); _sage_const_24700 = Integer(24700); _sage_const_62500 = Integer(62500); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_80 = Integer(80); _sage_const_1 = Integer(1); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_0 = Integer(0); _sage_const_0j = ComplexNumber(0, '0'); _sage_const_2j = ComplexNumber(0, '2'); _sage_const_1en6 = RealNumber('1e-6'); _sage_const_0p13 = RealNumber('0.13'); _sage_const_0p07j = ComplexNumber(0, '0.07'); _sage_const_0p08 = RealNumber('0.08'); _sage_const_0p11j = ComplexNumber(0, '0.11'); _sage_const_4p046197656444178 = RealNumber('4.046197656444178'); _sage_const_200 = Integer(200); _sage_const_0p0 = RealNumber('0.0'); _sage_const_9 = Integer(9); _sage_const_10 = Integer(10); _sage_const_7 = Integer(7); _sage_const_11p5 = RealNumber('11.5'); _sage_const_10p0 = RealNumber('10.0'); _sage_const_8p0 = RealNumber('8.0'); _sage_const_6p5 = RealNumber('6.5')# Q-SERIE dilog genus-2 (TK tau) -- TAPPA 1: fondamenta.
# (1) nomi q_ij dalla matrice di Riemann tau (2x2) -> parametri d'espansione.
# (2) serie in NOME della theta[delta] genus-2 vs RiemannTheta (verifica mattone base).
# (3) ground-truth del DILOG Lambda(r) = int(A_ab dOmega - Omega dA_ab),
#     Omega=log[theta[d](w-e+)/theta[d](w-e-)] (3a specie), A_ab=parte abeliana source.
from sage.all import QQ
from sage.schemes.riemann_surfaces.riemann_surface import RiemannSurface as SageRS
from abelfunctions import RiemannTheta
import numpy as np
from scipy.integrate import quad
import itertools

M,a,J,Ehat = _sage_const_1p0 ,_sage_const_0p9 ,_sage_const_2p5 ,_sage_const_1p4 
Rs = PolynomialRing(QQ, ['s','Y']); s,Y = Rs.gens()
lam=[QQ(_sage_const_1200 ),QQ(-_sage_const_2300 ),QQ(-_sage_const_11428 ),QQ(-_sage_const_5519 ),QQ(_sage_const_24700 ),QQ(_sage_const_62500 )]
qpoly=sum(lam[i]*s**i for i in range(_sage_const_6 ))
X=SageRS(Y**_sage_const_2 -qpoly, prec=_sage_const_80 )
omega=np.array(X.matrix_of_integral_values([Rs(_sage_const_1 ),s]),dtype=complex)[:,:_sage_const_2 ]
tau=np.array(X.riemann_matrix(),dtype=complex); ominv=np.linalg.inv(omega)
print("tau =\n",np.round(tau,_sage_const_5 ))
print("Im(tau) diag =",np.round(np.diag(tau.imag),_sage_const_4 )," (grande => nome piccolo, serie converge)")
# nomi q_ij = exp(i pi tau_ij)
qm=np.array([[np.exp(_sage_const_1j *np.pi*tau[i,j]) for j in range(_sage_const_2 )] for i in range(_sage_const_2 )])
print("|q_11|,|q_22|,|q_12| =",[f"{abs(qm[_sage_const_0 ,_sage_const_0 ]):.4f}",f"{abs(qm[_sage_const_1 ,_sage_const_1 ]):.4f}",f"{abs(qm[_sage_const_0 ,_sage_const_1 ]):.4f}"])

# (2) serie in nome (somma reticolare troncata) della theta[delta] vs RiemannTheta
def theta_latt(z,av,bv,N=_sage_const_6 ):
    tot=_sage_const_0j 
    for n in itertools.product(range(-N,N+_sage_const_1 ),repeat=_sage_const_2 ):
        nn=np.array(n)+np.array(av)
        tot+=np.exp(_sage_const_1j *np.pi*(nn@tau@nn)+_sage_const_2j *np.pi*(nn@(np.array(z)+np.array(bv))))
    return tot
halfs=[np.array(v)/_sage_const_2  for v in itertools.product([_sage_const_0 ,_sage_const_1 ],repeat=_sage_const_2 )]
def theta_af(z,av,bv):
    av=np.array(av); bv=np.array(bv); zz=z+tau@av+bv
    pref=np.exp(_sage_const_1j *np.pi*(av@tau@av)+_sage_const_2j *np.pi*(av@(z+bv)))
    return pref*complex(RiemannTheta(zz,tau))
odd=[(av,bv) for av in halfs for bv in halfs if abs(theta_af(np.zeros(_sage_const_2 ),av,bv))<_sage_const_1en6 ]
av,bv=odd[_sage_const_1 ]
ztest=np.array([_sage_const_0p13 +_sage_const_0p07j ,-_sage_const_0p08 +_sage_const_0p11j ])
print("\nserie-nome theta[delta] vs RiemannTheta (N=6):",
      abs(theta_latt(ztest,av,bv)-theta_af(ztest,av,bv)))

# (3) ground-truth dilog
def qn(sv): return sum(float(lam[i])*sv**i for i in range(_sage_const_6 ))
rmin=_sage_const_4p046197656444178 ; s_b=_sage_const_1p0 /rmin
def Iu(s_to):
    U=np.sqrt(s_b-s_to)
    g0=lambda u:_sage_const_2 *u/np.sqrt(qn(s_b-u**_sage_const_2 )); g1=lambda u:_sage_const_2 *u*(s_b-u**_sage_const_2 )/np.sqrt(qn(s_b-u**_sage_const_2 ))
    return -np.array([quad(g0,_sage_const_0 ,U,limit=_sage_const_200 )[_sage_const_0 ],quad(g1,_sage_const_0 ,U,limit=_sage_const_200 )[_sage_const_0 ]])
def w_of(sv): return ominv@Iu(sv)
e_plus=w_of(_sage_const_0p0 ); e_minus=-e_plus
def Omega(rv):  # 3a specie: log theta-ratio
    w=w_of(_sage_const_1p0 /rv); return np.log(theta_af(w-e_plus,av,bv)/theta_af(w-e_minus,av,bv))
# A_ab (source abeliano) = int dEF - parte algebrica. Uso direttamente int dEF - Acal/sqrtS.
import sympy as sp
r,Es=sp.symbols('r E',positive=True); Ms,as_,Js=sp.Rational(_sage_const_1 ),sp.Rational(_sage_const_9 ,_sage_const_10 ),sp.Rational(_sage_const_5 ,_sage_const_2 )
Dl=r**_sage_const_2 -_sage_const_2 *Ms*r+as_**_sage_const_2 ; Em=(Es**_sage_const_2 -_sage_const_1 )*r+_sage_const_2 *Ms
Ssym=sp.expand(r*(r-_sage_const_2 *Ms)*Em*(r*Dl-Js**_sage_const_2 *Em)); Ksym=Js*r*(r-_sage_const_2 *Ms)*Em/Dl
dEF=sp.diff(Ksym/sp.sqrt(Ssym),Es).subs(Es,sp.Rational(_sage_const_7 ,_sage_const_5 ))
dEFn=sp.lambdify(r,dEF,'numpy')
def Sn(x):
    Dl=x**_sage_const_2 -_sage_const_2 *Ms*x+as_**_sage_const_2 ; E7=_sage_const_1p4 ; Emm=(E7**_sage_const_2 -_sage_const_1 )*x+_sage_const_2 *Ms
    return float(x*(x-_sage_const_2 *Ms)*Emm*(x*Dl-Js**_sage_const_2 *Emm))
r0=_sage_const_11p5 
def A_full(rv): return quad(dEFn,r0,rv,limit=_sage_const_200 )[_sage_const_0 ]   # dA_ab/dr ~ dEF (parte abeliana domina la variazione)
def dOmega(rv,h=_sage_const_1en6 ): return (Omega(rv+h)-Omega(rv-h))/(_sage_const_2 *h)
# Lambda = int(A dOmega - Omega dA), A=A_full (proxy), dA=dEF  -- GROUND TRUTH del peso-2
def dilog(rv):
    return quad(lambda x: A_full(x)*dOmega(x) - Omega(x)*dEFn(x), r0, rv, limit=_sage_const_80 )[_sage_const_0 ]
print("\n=== ground-truth dilog Lambda(r) = int(A dOmega - Omega dA) ===")
for rv in [_sage_const_10p0 ,_sage_const_8p0 ,_sage_const_6p5 ]:
    print(f"  r={rv}: Lambda={dilog(rv):+.6f}  Omega={Omega(rv).real:+.4f}+{Omega(rv).imag:+.4f}j")
print("\n=> nomi q_ij + serie-nome theta verificata + dilog ground-truth pronti.")
print("   TAPPA 2: espandere Omega(r) e Lambda in serie di nome (Kronecker-Eisenstein genus-2).")

