# -*- coding: utf-8 -*-


# This file was *autogenerated* from the file kerr_tau_dilog_qseries4.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p0 = RealNumber('1.0'); _sage_const_0p9 = RealNumber('0.9'); _sage_const_2p5 = RealNumber('2.5'); _sage_const_1p4 = RealNumber('1.4'); _sage_const_1200 = Integer(1200); _sage_const_2300 = Integer(2300); _sage_const_11428 = Integer(11428); _sage_const_5519 = Integer(5519); _sage_const_24700 = Integer(24700); _sage_const_62500 = Integer(62500); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_80 = Integer(80); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_2j = ComplexNumber(0, '2'); _sage_const_8 = Integer(8); _sage_const_1en6 = RealNumber('1e-6'); _sage_const_4p046197656444178 = RealNumber('4.046197656444178'); _sage_const_200 = Integer(200); _sage_const_0p0 = RealNumber('0.0'); _sage_const_9 = Integer(9); _sage_const_10 = Integer(10); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11p5 = RealNumber('11.5'); _sage_const_60 = Integer(60); _sage_const_10p0 = RealNumber('10.0'); _sage_const_8p0 = RealNumber('8.0'); _sage_const_6p5 = RealNumber('6.5')# (B) q-serie dilog genus-2 -- TAPPA 4 (attacco frontiera).
# Milestone verificabile: il dilog Lambda = int Omega dA e' calcolabile con la SERIE DI NOME
# di Omega (tappa 3), non solo con la theta diretta. Poi imposto la struttura Kronecker-Eisenstein.
# Lambda(r) = int_{r0}^r Omega(r') (dA/dr') dr' ; confronto Omega_nome vs Omega_diretto nell'integrando.
from sage.all import QQ
from sage.schemes.riemann_surfaces.riemann_surface import RiemannSurface as SageRS
from abelfunctions import RiemannTheta
import numpy as np, sympy as sp
from scipy.integrate import quad
import itertools

M,a,J,Ehat=_sage_const_1p0 ,_sage_const_0p9 ,_sage_const_2p5 ,_sage_const_1p4 
Rs=PolynomialRing(QQ,['s','Y']);s,Y=Rs.gens()
lam=[QQ(_sage_const_1200 ),QQ(-_sage_const_2300 ),QQ(-_sage_const_11428 ),QQ(-_sage_const_5519 ),QQ(_sage_const_24700 ),QQ(_sage_const_62500 )]
qpoly=sum(lam[i]*s**i for i in range(_sage_const_6 ));X=SageRS(Y**_sage_const_2 -qpoly,prec=_sage_const_80 )
omega=np.array(X.matrix_of_integral_values([Rs(_sage_const_1 ),s]),dtype=complex)[:,:_sage_const_2 ]
tau=np.array(X.riemann_matrix(),dtype=complex);ominv=np.linalg.inv(omega)
taup=-np.linalg.inv(tau);tinv=np.linalg.inv(tau)
halfs=[np.array(v)/_sage_const_2  for v in itertools.product([_sage_const_0 ,_sage_const_1 ],repeat=_sage_const_2 )]
def theta_af(z,av,bv,t):
    av=np.array(av);bv=np.array(bv);zz=z+t@av+bv
    return np.exp(_sage_const_1j *np.pi*(av@t@av)+_sage_const_2j *np.pi*(av@(z+bv)))*complex(RiemannTheta(zz,t))
def theta0_latt(z,t,N=_sage_const_8 ):
    return sum(np.exp(_sage_const_1j *np.pi*(np.array(n)@t@np.array(n))+_sage_const_2j *np.pi*(np.array(n)@np.array(z)))
              for n in itertools.product(range(-N,N+_sage_const_1 ),repeat=_sage_const_2 ))
odd=[(av,bv) for av in halfs for bv in halfs if abs(theta_af(np.zeros(_sage_const_2 ),av,bv,tau))<_sage_const_1en6 ]
av,bv=odd[_sage_const_1 ]
def qn(sv): return sum(float(lam[i])*sv**i for i in range(_sage_const_6 ))
rmin=_sage_const_4p046197656444178 ;s_b=_sage_const_1p0 /rmin
def Iu(sv):
    U=np.sqrt(s_b-sv);g0=lambda u:_sage_const_2 *u/np.sqrt(qn(s_b-u**_sage_const_2 ));g1=lambda u:_sage_const_2 *u*(s_b-u**_sage_const_2 )/np.sqrt(qn(s_b-u**_sage_const_2 ))
    return -np.array([quad(g0,_sage_const_0 ,U,limit=_sage_const_200 )[_sage_const_0 ],quad(g1,_sage_const_0 ,U,limit=_sage_const_200 )[_sage_const_0 ]])
def w_of(sv): return ominv@Iu(sv)
e_plus=w_of(_sage_const_0p0 );e_minus=-e_plus
def Omega_direct(rv):
    w=w_of(_sage_const_1p0 /rv);return np.log(theta_af(w-e_plus,av,bv,tau)/theta_af(w-e_minus,av,bv,tau))
def Omega_nome(rv):
    w=w_of(_sage_const_1p0 /rv);z1=w-e_plus;z2=w-e_minus;zeta1=z1+tau@av+bv;zeta2=z2+tau@av+bv
    Lth=np.log(theta0_latt(tinv@zeta1,taup)/theta0_latt(tinv@zeta2,taup))
    return Lth-_sage_const_1j *np.pi*(zeta1@tinv@zeta1-zeta2@tinv@zeta2)+_sage_const_2j *np.pi*(av@(e_minus-e_plus))
def branch(d): return d.real+_sage_const_1j *((d.imag+np.pi)%(_sage_const_2 *np.pi)-np.pi)
# source 2a specie dA/dr = dEF (parte abeliana)
r,Es=sp.symbols('r E',positive=True);Ms,as_,Js=sp.Rational(_sage_const_1 ),sp.Rational(_sage_const_9 ,_sage_const_10 ),sp.Rational(_sage_const_5 ,_sage_const_2 )
Dl=r**_sage_const_2 -_sage_const_2 *Ms*r+as_**_sage_const_2 ;Em=(Es**_sage_const_2 -_sage_const_1 )*r+_sage_const_2 *Ms
Ksym=Js*r*(r-_sage_const_2 *Ms)*Em/Dl;Ssym=sp.expand(r*(r-_sage_const_2 *Ms)*Em*(r*Dl-Js**_sage_const_2 *Em))
dEF=sp.diff(Ksym/sp.sqrt(Ssym),Es).subs(Es,sp.Rational(_sage_const_7 ,_sage_const_5 ));dEFn=sp.lambdify(r,dEF,'numpy')
r0=_sage_const_11p5 
# Lambda con Omega DIRETTO (ground truth) e con Omega NOME
def Lam(rv,Omfun):
    return quad(lambda x: branch(Omfun(x))*dEFn(x), r0, rv, limit=_sage_const_60 )[_sage_const_0 ] if False else            quad(lambda x: Omfun(x).real*dEFn(x), r0, rv, limit=_sage_const_60 )[_sage_const_0 ]
print("=== TAPPA 4 milestone: dilog Lambda con Omega_nome vs Omega_diretto ===")
for rv in [_sage_const_10p0 ,_sage_const_8p0 ,_sage_const_6p5 ]:
    Ld=Lam(rv,lambda x:Omega_direct(x)); Ln=Lam(rv,lambda x:branch(Omega_nome(x)-Omega_direct(x))+Omega_direct(x))
    # uso Re(Omega): la parte Re combacia esattamente (tappa 3). Verifico con Omega_nome puro:
    Ln2=quad(lambda x: Omega_nome(x).real*dEFn(x), r0, rv, limit=_sage_const_60 )[_sage_const_0 ]
    print(f"  r={rv}: Lambda(Om_dir)={Ld:+.6f}  Lambda(Om_nome)={Ln2:+.6f}  diff={abs(Ld-Ln2):.1e}")
print("\n=> se diff~0: il dilog E' calcolato via la SERIE DI NOME di Omega (tappa 3 alimenta Lambda).")
print("   STRUTTURA Kronecker-Eisenstein: Lambda=Sum_{n,m} c_n d_m e^{2pi i(n+m)w}/(2pi i(n+m)),")
print("   c_n=Fourier(Omega), d_m=Fourier(2a specie). Resummazione analitica chiusa = frontiera aperta.")

