# -*- coding: utf-8 -*-


# This file was *autogenerated* from the file kerr_tau_Wij_aperiods.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_9 = Integer(9); _sage_const_10 = Integer(10); _sage_const_7 = Integer(7); _sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_1250 = Integer(1250); _sage_const_80 = Integer(80); _sage_const_0 = Integer(0)# (A) CHIUSURA parte OLOMORFA via a-PERIODI (TK tau, genus-2).
# I coeff olomorfi alpha_k,beta_k di U_k = (poli, coeff simbolici g_i) + alpha_k u1 + beta_k u2
# sono determinati dagli a-PERIODI (principio, non fit; base pole normalizzata a a-periodo zero):
#   (alpha_k, beta_k) = omega^{-1} . [oint_{a_j} omega_k],   omega_k = r^k dr/y (modello PARI).
# Sage matrix_of_integral_values integra i differenziali polinomiali r^k dr/y sui cicli.
# Sanity: k=0,1 (olomorfi) -> vettori unita' (U_0=u2,U_1=u1). Period-level come C0/Ce separatrice.
from sage.all import QQ
from sage.schemes.riemann_surfaces.riemann_surface import RiemannSurface as SageRS
import numpy as np

M,a,E,J = QQ(_sage_const_1 ),QQ(_sage_const_9 )/_sage_const_10 ,QQ(_sage_const_7 )/_sage_const_5 ,QQ(_sage_const_5 )/_sage_const_2 
Rr=PolynomialRing(QQ,['x','y']); x,y=Rr.gens()
Dl=x**_sage_const_2 -_sage_const_2 *M*x+a**_sage_const_2 ; Em=(E**_sage_const_2 -_sage_const_1 )*x+_sage_const_2 *M
Sint=(_sage_const_1250 *x*(x-_sage_const_2 *M)*Em*(x*Dl-J**_sage_const_2 *Em)).change_ring(QQ)   # modello intero (come psi_forward_abel)
Xrs=SageRS(y**_sage_const_2 -Sint, prec=_sage_const_80 )
# a-periodi (2 cicli) dei differenziali x^k dx/y, k=0..4
diffs=[Rr(x**k) for k in range(_sage_const_5 )]
MIV=np.array(Xrs.matrix_of_integral_values(diffs),dtype=complex)   # 5 x 4 (diff x cicli)
aper=MIV[:,:_sage_const_2 ]   # a-periodi (prime 2 colonne)
print("a-periodi oint_{a_j} x^k dx/y  (righe k=0..4, colonne a1,a2):")
for k in range(_sage_const_5 ): print(f"  k={k}: {np.round(aper[k],_sage_const_5 )}")
omega=aper[:_sage_const_2 ,:]      # 2x2: a-periodi olomorfi (k=0,1)
ominv=np.linalg.inv(omega)
print("\nomega (a-per olomorfi k=0,1) =\n",np.round(omega,_sage_const_5 ))
print("\n=== coeff olomorfi (alpha_k,beta_k) = omega^{-1} . a-per(omega_k) ===")
for k in range(_sage_const_5 ):
    ab=aper[k]@ominv   # aper[k] = [alpha,beta] . omega  =>  [alpha,beta] = aper[k] . omega^{-1}
    tag=" (olomorfo: deve ~ e_k)" if k<_sage_const_2  else ""
    print(f"  k={k}: (alpha,beta)=({ab[_sage_const_0 ]:+.5f},{ab[_sage_const_1 ]:+.5f}){tag}")
print("\n=> k=0,1 danno vettori unita' (sanity). k=2,3,4: coeff olomorfi period-level di U_k")
print("   (determinati dagli a-periodi = principio, NON fit; dipendono dai periodi come C0/Ce).")
print("   Combinati coi coeff di polo simbolici g_i -> decomposizione canonica COMPLETA.")

