

# This file was *autogenerated* from the file vaidya_thirdkind_fay.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p0 = RealNumber('1.0'); _sage_const_1p4 = RealNumber('1.4'); _sage_const_2p5 = RealNumber('2.5'); _sage_const_1 = Integer(1); _sage_const_7 = Integer(7); _sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_90 = Integer(90); _sage_const_2p0 = RealNumber('2.0'); _sage_const_0 = Integer(0); _sage_const_200 = Integer(200); _sage_const_1en9 = RealNumber('1e-9'); _sage_const_40p0 = RealNumber('40.0'); _sage_const_300 = Integer(300); _sage_const_1en6 = RealNumber('1e-6'); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_2j = ComplexNumber(0, '2'); _sage_const_0p6 = RealNumber('0.6'); _sage_const_11p0 = RealNumber('11.0'); _sage_const_36 = Integer(36); _sage_const_1en30 = RealNumber('1e-30')# Chiusura di FAY della terza specie d'ORIZZONTE in Vaidya.
# Lettera terza specie: eta_h = dr/(r-2m), polo SEMPLICE (residuo 2) al punto di
# Weierstrass r=2m + poli all'infinito. (NB: L_2m e' invece 2a specie -> zeta di Klein.)
# Claim (Fay, come L in Kerr ma centrato sull'orizzonte):
#   int eta_h = rho * log[ theta[delta](w-e_h) / theta[delta](w-e_inf) ] + holo,
#   delta ODD. Verifica round-trip: d/dr log-ratio = c0/(r-2m) + c1/sqrt(S) + c2 r/sqrt(S)
#   (holo = normalizzazione a-periodi), residuo lstsq ~ 0.
from sage.all import QQ
from sage.schemes.riemann_surfaces.riemann_surface import RiemannSurface as SageRS
from abelfunctions import RiemannTheta
import numpy as np
from scipy.integrate import quad
import itertools

M, E, J = _sage_const_1p0 , _sage_const_1p4 , _sage_const_2p5    # Vaidya frozen (a=0), m=1
# sestico S(r)=r(r-2m)DE[r^2(r-2m)-J^2 DE], DE=(E^2-1)r+2m  (coeff razionali)
Rr = PolynomialRing(QQ, ['x','Y']); x, Y = Rr.gens()
Em, Es, Js = QQ(_sage_const_1 ), QQ(_sage_const_7 )/_sage_const_5 , QQ(_sage_const_5 )/_sage_const_2 
DE = (Es**_sage_const_2 -_sage_const_1 )*x + _sage_const_2 *Em
S = Rr(x*(x-_sage_const_2 *Em)*DE*(x**_sage_const_2 *(x-_sage_const_2 *Em) - Js**_sage_const_2 *DE))
Spoly = S  # y^2 = S(x), sestico -> genere 2
X = SageRS(Y**_sage_const_2  - Spoly, prec=_sage_const_90 )
omega = np.array(X.matrix_of_integral_values([Rr(_sage_const_1 ), x]), dtype=complex)[:, :_sage_const_2 ]  # a-per (1,x)/Y
tau = np.array(X.riemann_matrix(), dtype=complex)
ominv = np.linalg.inv(omega)

def Sn(rv):
    DEn = (E**_sage_const_2 -_sage_const_1 )*rv + _sage_const_2 *M
    return rv*(rv-_sage_const_2 *M)*DEn*(rv**_sage_const_2 *(rv-_sage_const_2 *M) - J**_sage_const_2 *DEn)
r_h = _sage_const_2p0 *M                      # orizzonte = branch point (base della mappa di Abel)

# Abel map w(r) = ominv @ [int_{r_h}^r 1/sqrt(S), int_{r_h}^r x/sqrt(S)]  (reg. al branch)
def Iu(r_to):   # int_{r_h}^{r_to} (1,x)/sqrt(S) dx, sub x=r_h+u^2 vicino al branch
    U = np.sqrt(abs(r_to - r_h)); sgn = _sage_const_1p0  if r_to > r_h else -_sage_const_1p0 
    g0 = lambda u: _sage_const_2 *u*(_sage_const_1p0 )/np.sqrt(abs(Sn(r_h+sgn*u**_sage_const_2 )))
    g1 = lambda u: _sage_const_2 *u*(r_h+sgn*u**_sage_const_2 )/np.sqrt(abs(Sn(r_h+sgn*u**_sage_const_2 )))
    I0 = quad(g0, _sage_const_0 , U, limit=_sage_const_200 )[_sage_const_0 ]; I1 = quad(g1, _sage_const_0 , U, limit=_sage_const_200 )[_sage_const_0 ]
    return sgn*np.array([I0, I1])
def w_of(r_to): return ominv @ Iu(r_to)
e_h = w_of(r_h + _sage_const_1en9 )           # ~0 (base al branch orizzonte)
# immagine di infinito: int_{r_h}^{inf} (1,x)/sqrt(S) (converge: (1,x)/r^3)
def Iinf():
    g0 = lambda t: (_sage_const_1p0 )/np.sqrt(abs(Sn(_sage_const_1p0 /t)))*(_sage_const_1p0 /t**_sage_const_2 )   # x=1/t, dx=-dt/t^2
    g1 = lambda t: (_sage_const_1p0 /t)/np.sqrt(abs(Sn(_sage_const_1p0 /t)))*(_sage_const_1p0 /t**_sage_const_2 )
    # from r_h to inf: split r_h..R0 (direct) + R0..inf (sub)
    R0 = _sage_const_40p0 
    d0 = quad(lambda xx: _sage_const_1p0 /np.sqrt(abs(Sn(xx))), r_h+_sage_const_1en9 , R0, limit=_sage_const_300 )[_sage_const_0 ]
    d1 = quad(lambda xx: xx/np.sqrt(abs(Sn(xx))), r_h+_sage_const_1en9 , R0, limit=_sage_const_300 )[_sage_const_0 ]
    t0 = quad(g0, _sage_const_1en6 , _sage_const_1p0 /R0, limit=_sage_const_300 )[_sage_const_0 ]; t1 = quad(g1, _sage_const_1en6 , _sage_const_1p0 /R0, limit=_sage_const_300 )[_sage_const_0 ]
    return np.array([d0+t0, d1+t1])
e_inf = ominv @ Iinf()

# caratteristiche half-integer; odd = theta[delta](0)=0
def theta_d(z, av, bv, grad=False):
    av = np.array(av); bv = np.array(bv); zz = z + tau@av + bv
    pref = np.exp(_sage_const_1j *np.pi*(av@tau@av) + _sage_const_2j *np.pi*(av@(z+bv)))
    th = complex(RiemannTheta(zz, tau))
    if not grad: return pref*th
    g = np.array([complex(RiemannTheta(zz, tau, derivs=[e])) for e in ([_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ])])
    return _sage_const_2j *np.pi*av + g/th   # grad_z log theta[delta]
halfs = [np.array(v)/_sage_const_2  for v in itertools.product([_sage_const_0 ,_sage_const_1 ], repeat=_sage_const_2 )]
odd = [(av,bv) for av in halfs for bv in halfs if abs(theta_d(np.zeros(_sage_const_2 ),av,bv))<_sage_const_1en6 ]
print("caratteristiche ODD:", len(odd))

# campiona orbita (tra orizzonte e r0), costruisci basi
rg = np.linspace(r_h+_sage_const_0p6 , _sage_const_11p0 , _sage_const_36 )
inv_h = _sage_const_1p0 /(rg - _sage_const_2 *M)                       # terza specie letter
sq = np.sqrt(np.abs(Sn(rg)))
hol0 = _sage_const_1p0 /sq; hol1 = rg/sq                  # 2 olomorfi (2a specie base)
W = np.array([w_of(rv) for rv in rg])
dwdr = (ominv @ np.vstack([hol0, hol1])).T   # dw/dr = ominv @ (du_i/dr)
basis = np.vstack([inv_h, hol0, hol1]).T     # (N,3): {1/(r-2m), 1/sqrtS, r/sqrtS}

print("\n delta#  residuo(d log-ratio ~ c0/(r-2m)+holo)   c0")
best = None
for k,(av,bv) in enumerate(odd):
    D = np.array([ (theta_d(W[i]-e_h,av,bv,True)-theta_d(W[i]-e_inf,av,bv,True)) @ dwdr[i]
                   for i in range(len(rg))])
    coef,_,_,_ = np.linalg.lstsq(basis, D, rcond=None)
    resid = np.max(np.abs(basis@coef - D))/max(np.max(np.abs(D)),_sage_const_1en30 )
    print(f"  {k}: {resid:.3e}   c0={coef[_sage_const_0 ]:+.4f}")
    if best is None or resid<best[_sage_const_0 ]: best=(resid,k,coef)
print(f"\nMIGLIORE: delta #{best[_sage_const_1 ]}, residuo rel {best[_sage_const_0 ]:.2e}, c0={best[_sage_const_2 ][_sage_const_0 ]:.4f}")
print("=> se residuo ~0: eta_h (3a specie orizzonte) = log(theta-ratio) di FAY, CONFERMATO.")

