# -*- coding: utf-8 -*-


# This file was *autogenerated* from the file vaidya_dilog_qseries.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p0 = RealNumber('1.0'); _sage_const_1p4 = RealNumber('1.4'); _sage_const_2p5 = RealNumber('2.5'); _sage_const_24 = Integer(24); _sage_const_46 = Integer(46); _sage_const_248 = Integer(248); _sage_const_112 = Integer(112); _sage_const_575 = Integer(575); _sage_const_1250 = Integer(1250); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_80 = Integer(80); _sage_const_1 = Integer(1); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_0 = Integer(0); _sage_const_2j = ComplexNumber(0, '2'); _sage_const_8 = Integer(8); _sage_const_1en6 = RealNumber('1e-6'); _sage_const_7 = Integer(7); _sage_const_5 = Integer(5); _sage_const_6p25 = RealNumber('6.25'); _sage_const_3 = Integer(3); _sage_const_200 = Integer(200); _sage_const_0p0 = RealNumber('0.0'); _sage_const_12p0 = RealNumber('12.0'); _sage_const_10p = RealNumber('10.'); _sage_const_8p = RealNumber('8.'); _sage_const_6p5 = RealNumber('6.5'); _sage_const_60 = Integer(60); _sage_const_8p0 = RealNumber('8.0'); _sage_const_4 = Integer(4)# q-serie dilog genus-2 VAIDYA generico (a=0, param m). Template TK-tau: naming theta[delta]
# + Omega=log theta-ratio nome-serie + dilog Lambda split Q(elem)+L(dilog), convergenza nome.
from sage.all import QQ
from sage.schemes.riemann_surfaces.riemann_surface import RiemannSurface as SageRS
from abelfunctions import RiemannTheta
import numpy as np, sympy as sp
from scipy.integrate import quad
import itertools
mfloat,Efloat,Jfloat=_sage_const_1p0 ,_sage_const_1p4 ,_sage_const_2p5 
Rs=PolynomialRing(QQ,['s','Y']);s,Y=Rs.gens()
lam=[QQ(_sage_const_24 ),QQ(-_sage_const_46 ),QQ(-_sage_const_248 ),QQ(-_sage_const_112 ),QQ(_sage_const_575 ),QQ(_sage_const_1250 )]   # Vaidya odd model
qpoly=sum(lam[i]*s**i for i in range(_sage_const_6 )); X=SageRS(Y**_sage_const_2 -qpoly,prec=_sage_const_80 )
omega=np.array(X.matrix_of_integral_values([Rs(_sage_const_1 ),s]),dtype=complex)[:,:_sage_const_2 ]
tau=np.array(X.riemann_matrix(),dtype=complex);ominv=np.linalg.inv(omega)
taup=-np.linalg.inv(tau);tinv=np.linalg.inv(tau)
print("nomi tau':",[f"{abs(np.exp(_sage_const_1j *np.pi*taup[i,j])):.4f}" for i,j in [(_sage_const_0 ,_sage_const_0 ),(_sage_const_1 ,_sage_const_1 ),(_sage_const_0 ,_sage_const_1 )]])
halfs=[np.array(v)/_sage_const_2  for v in itertools.product([_sage_const_0 ,_sage_const_1 ],repeat=_sage_const_2 )]
def theta_af(z,av,bv,t):
    av=np.array(av);bv=np.array(bv);zz=z+t@av+bv
    return np.exp(_sage_const_1j *np.pi*(av@t@av)+_sage_const_2j *np.pi*(av@(z+bv)))*complex(RiemannTheta(zz,t))
def theta0_latt(z,t,N=_sage_const_8 ):
    return sum(np.exp(_sage_const_1j *np.pi*(np.array(n)@t@np.array(n))+_sage_const_2j *np.pi*(np.array(n)@np.array(z)))
              for n in itertools.product(range(-N,N+_sage_const_1 ),repeat=_sage_const_2 ))
odd=[(av,bv) for av in halfs for bv in halfs if abs(theta_af(np.zeros(_sage_const_2 ),av,bv,tau))<_sage_const_1en6 ]
av,bv=odd[_sage_const_1 ]
def qn(sv): return sum(float(lam[i])*sv**i for i in range(_sage_const_6 ))
# curva even + sorgente dm F (Vaidya)
r,m,E,J=sp.symbols('r m E J')
DE=(E**_sage_const_2 -_sage_const_1 )*r+_sage_const_2 *m; S=sp.expand(r*(r-_sage_const_2 *m)*DE*(r**_sage_const_2 *(r-_sage_const_2 *m)-J**_sage_const_2 *DE)); K=J*DE
dmF=sp.diff(K/sp.sqrt(S),m).subs({m:_sage_const_1 ,E:sp.Rational(_sage_const_7 ,_sage_const_5 ),J:sp.Rational(_sage_const_5 ,_sage_const_2 )})
dmFn=sp.lambdify(r,dmF,'numpy')
def Sn(x):
    E7=_sage_const_1p4 ;DEn=(E7**_sage_const_2 -_sage_const_1 )*x+_sage_const_2 ; return float(x*(x-_sage_const_2 )*DEn*(x**_sage_const_2 *(x-_sage_const_2 )-_sage_const_6p25 *DEn))
# turning e branch points (per w_of base)
Scoef=[float(c) for c in sp.Poly(S.subs({m:_sage_const_1 ,E:sp.Rational(_sage_const_7 ,_sage_const_5 ),J:sp.Rational(_sage_const_5 ,_sage_const_2 )}),r).all_coeffs()]
rts=np.sort(np.real(np.roots(Scoef))); rmin=rts[rts>_sage_const_3 ][_sage_const_0 ] if any(rts>_sage_const_3 ) else rts[-_sage_const_1 ]
s_b=_sage_const_1p0 /rmin
def Iu(sv):
    U=np.sqrt(abs(s_b-sv));g0=lambda u:_sage_const_2 *u/np.sqrt(abs(qn(s_b-u**_sage_const_2 )));g1=lambda u:_sage_const_2 *u*(s_b-u**_sage_const_2 )/np.sqrt(abs(qn(s_b-u**_sage_const_2 )))
    sg=-_sage_const_1p0  if sv<s_b else _sage_const_1p0 
    return sg*np.array([quad(g0,_sage_const_0 ,U,limit=_sage_const_200 )[_sage_const_0 ],quad(g1,_sage_const_0 ,U,limit=_sage_const_200 )[_sage_const_0 ]])
def w_of(sv): return ominv@Iu(sv)
e_plus=w_of(_sage_const_0p0 );e_minus=-e_plus
def Q_part(rv):
    w=w_of(_sage_const_1p0 /rv);z1=w-e_plus;z2=w-e_minus;zeta1=z1+tau@av+bv;zeta2=z2+tau@av+bv
    return (-_sage_const_1j *np.pi*(zeta1@tinv@zeta1-zeta2@tinv@zeta2)+_sage_const_2j *np.pi*(av@(e_minus-e_plus))).real
def L_partN(rv,N=_sage_const_8 ):
    w=w_of(_sage_const_1p0 /rv);zeta1=(w-e_plus)+tau@av+bv;zeta2=(w-e_minus)+tau@av+bv
    return np.log(theta0_latt(tinv@zeta1,taup,N)/theta0_latt(tinv@zeta2,taup,N)).real
r0=_sage_const_12p0 
print("\n=== VAIDYA dilog: split Lambda = int Q dA (elem) + int L dA (dilog) ===")
for rv in [_sage_const_10p ,_sage_const_8p ,_sage_const_6p5 ]:
    LQ=quad(lambda x:Q_part(x)*dmFn(x),r0,rv,limit=_sage_const_60 )[_sage_const_0 ]
    LL=quad(lambda x:L_partN(x)*dmFn(x),r0,rv,limit=_sage_const_60 )[_sage_const_0 ]
    print(f"  r={rv}: int Q dA(elem)={LQ:+.6f}  int L dA(dilog)={LL:+.6f}")
print("\n=== convergenza q-serie del dilog in ordine di nome N (r=8) ===")
rv=_sage_const_8p0 ; ref=quad(lambda x:L_partN(x,_sage_const_8 )*dmFn(x),r0,rv,limit=_sage_const_60 )[_sage_const_0 ]
for N in [_sage_const_1 ,_sage_const_2 ,_sage_const_3 ,_sage_const_4 ,_sage_const_6 ]:
    val=quad(lambda x:L_partN(x,N)*dmFn(x),r0,rv,limit=_sage_const_60 )[_sage_const_0 ]
    print(f"  N={N}: int L dA = {val:+.7f}  |diff da N=8| = {abs(val-ref):.1e}")
print("\n=> VAIDYA: dilog = elem + serie di nome KE genus-2 convergente. Naming theta[delta] agli e_pm.")

